.github/draft-release-notes-config.yml
.github/workflows/cypress-workflow.yml
.github/workflows/release-workflow.yml
README.md
cypress/integration/managed_indices_spec.js
cypress/support/constants.js
opensearch_dashboards.json
package.json
public/pages/ChangePolicy/components/NewPolicy/__snapshots__/NewPolicy.test.tsx.snap
public/pages/ChangePolicy/containers/ChangePolicy/__snapshots__/ChangePolicy.test.tsx.snap
public/pages/CreatePolicy/components/DefinePolicy/__snapshots__/DefinePolicy.test.tsx.snap
public/pages/CreatePolicy/containers/CreatePolicy/__snapshots__/CreatePolicy.test.tsx.snap
public/pages/CreateRollup/components/AdvancedAggregation/AdvancedAggregation.tsx
public/utils/constants.ts
release-notes/create-release-notes.py
server/models/interfaces.ts
server/services/IndexService.ts
server/utils/constants.ts
server/utils/helpers.ts

N/A
* Updates the API calls to use the new `_plugins/` endpoint prefix in favor of the legacy `_opendistro/*` endpoint prefix.
* Updates the settings naming to use the new `plugins` prefix in favor of the legacy `opendistro` prefix.
* Updates the documentation links to point to the new home for docs: https://docs-beta.opensearch.org/
Performed local testing with cypress tests and end to end testing, which succeeded. Github workflow currently failing since Alerting and ISM github repos are not updated yet.
(b) The contribution is based …

Update API, settings, and doc link renaming

---

package.json
public/pages/CreateTransform/components/DefineTransforms/DefineTransforms.tsx
public/pages/CreateTransform/components/PreviewOptions/Panels/EditTransformPanel/EditTransformPanel.tsx
public/pages/CreateTransform/components/PreviewOptions/Panels/EditTransformPanel/index.ts
public/pages/CreateTransform/components/PreviewOptions/PreviewOptions.tsx
public/pages/CreateTransform/components/PreviewTransform/PreviewTransform.tsx
public/pages/CreateTransform/containers/CreateTransformForm/CreateTransformForm.tsx
public/pages/CreateTransform/containers/DefineTransformsStep/DefineTransformsStep.tsx
public/pages/CreateTransform/utils/helpers.ts
yarn.lock

*Issue #, if available:* N/A
- Add the functionality to edit transformation name. 
- Modify the "preview column" option icon from a "delete" icon to "edit" icon. 
- Add a helper function `isGroupBy` to determine the type of transformation.
_Screenshots:_ 
On step 2 of create transform:
When clicking the edit transform icon button:
After selecting "Edit transformation":
Validation of duplicate name: 
license and I have the right under …

Support edit transformation name

---

README.md
cypress.json
cypress/support/index.js

* Provide mechanism to set the OpenSearch and Dashboards endpoint when running cypress tests.
* Fix broken link
N/A

Adding support to correctly set the dashboards and opensearch endpoint

---

public/pages/VisualCreatePolicy/components/EuiFormCustomLabel/EuiFormCustomLabel.test.tsx
public/pages/VisualCreatePolicy/components/EuiFormCustomLabel/EuiFormCustomLabel.tsx
public/pages/VisualCreatePolicy/components/EuiFormCustomLabel/__snapshots__/EuiFormCustomLabel.test.tsx.snap
public/pages/VisualCreatePolicy/components/EuiFormCustomLabel/index.ts

UI/UX team wanted to move help text under title instead of below input. EuiForm component didn't support that, so this is just a small custom label component to use instead.
After All files                                                                             |   47.88 |    41.29 |   44.11 |   48.42 | …

Adds custom label to use with EuiForm component

---

public/pages/VisualCreatePolicy/components/FlyoutFooter/FlyoutFooter.test.tsx
public/pages/VisualCreatePolicy/components/FlyoutFooter/FlyoutFooter.tsx
public/pages/VisualCreatePolicy/components/FlyoutFooter/__snapshots__/FlyoutFooter.test.tsx.snap
public/pages/VisualCreatePolicy/components/FlyoutFooter/index.ts

Adds a reusable flyout footer as we have multiple "views" of the flyout for creation flow.
After All files                                                                             |   47.88 |    41.16 |   44.11 |   48.42 | …

Adds reusable flyout footer

---

public/pages/VisualCreatePolicy/components/Badge/Badge.test.tsx
public/pages/VisualCreatePolicy/components/Badge/Badge.tsx
public/pages/VisualCreatePolicy/components/Badge/__snapshots__/Badge.test.tsx.snap
public/pages/VisualCreatePolicy/components/Badge/index.ts

Adds a small badge component to show number of actions and transitions in new visual UI
After All files                                                                             |   47.88 |    41.14 |   44.11 |   48.42 | …

Adds a small Badge component

---

public/pages/VisualCreatePolicy/components/LegacyNotification/LegacyNotification.test.tsx
public/pages/VisualCreatePolicy/components/LegacyNotification/LegacyNotification.tsx
public/pages/VisualCreatePolicy/components/LegacyNotification/__snapshots__/LegacyNotification.test.tsx.snap
public/pages/VisualCreatePolicy/components/LegacyNotification/index.ts
public/pages/VisualCreatePolicy/utils/constants.ts

For error notification and notification action we will have to support legacy destinations and new channels.
For legacy destinations we simply support a JSON editor.
After All files                                                                             |   47.91 |    41.17 |   44.18 |   48.45 | …

Adds legacy notification UI input

---

public/pages/VisualCreatePolicy/components/PolicyInfo/PolicyInfo.test.tsx
public/pages/VisualCreatePolicy/components/PolicyInfo/PolicyInfo.tsx
public/pages/VisualCreatePolicy/components/PolicyInfo/__snapshots__/PolicyInfo.test.tsx.snap
public/pages/VisualCreatePolicy/components/PolicyInfo/index.ts

Adds policy info section for new UI
Before recent UI All files                                                                             |   47.84 |    41.09 |   44.05 |   48.38 |
After All files                                                                             |   48.19 |    41.54 |   44.55 |   48.77 |
PolicyInfo.tsx                                                                      |     100 |      100 |     100 |     100 |
By submitting this pull …

Adds policy info section for new UI

---

models/interfaces.ts
public/components/ContentPanel/ContentPanel.tsx
public/pages/ChangePolicy/components/NewPolicy/__snapshots__/NewPolicy.test.tsx.snap
public/pages/ChangePolicy/containers/ChangePolicy/__snapshots__/ChangePolicy.test.tsx.snap
public/pages/CreatePolicy/components/DefinePolicy/__snapshots__/DefinePolicy.test.tsx.snap
public/pages/CreatePolicy/containers/CreatePolicy/__snapshots__/CreatePolicy.test.tsx.snap
public/pages/VisualCreatePolicy/containers/ErrorNotification/ErrorNotification.test.tsx
public/pages/VisualCreatePolicy/containers/ErrorNotification/ErrorNotification.tsx
public/pages/VisualCreatePolicy/containers/ErrorNotification/__snapshots__/ErrorNotification.test.tsx.snap
public/pages/VisualCreatePolicy/containers/ErrorNotification/index.ts
public/utils/constants.ts

Adds container for error notification that switches between legacy and channel UIs.
Before recent UI All files                                                                             |   47.84 |    41.09 |   44.05 |   48.38 |
After All files                                                                             |   48.59 |    42.11 |   45.06 |   49.18 |                                                                                                    
By …

Adds error notification UI container and updates snapshots

---

models/interfaces.ts
public/pages/PolicyDetails/components/DeleteModal/DeleteModal.test.tsx
public/pages/PolicyDetails/components/DeleteModal/DeleteModal.tsx
public/pages/PolicyDetails/components/DeleteModal/__snapshots__/DeleteModal.test.tsx.snap
public/pages/PolicyDetails/components/DeleteModal/index.ts
public/pages/PolicyDetails/components/PolicySettings/PolicySettings.test.tsx
public/pages/PolicyDetails/components/PolicySettings/PolicySettings.tsx
public/pages/PolicyDetails/components/PolicySettings/__snapshots__/PolicySettings.test.tsx.snap
public/pages/PolicyDetails/components/PolicySettings/index.ts

Signed-off-by: Eric Lobdell <lobdelle@amazon.com>
Adds PolicySettings and DeleteModal components used by the PolicyDetails UI. PolicySettings is the upper render box that shows basic details of the given policy, excluding States display. DeleteModal is responsible for confirming that the user wants to delete the policy.
- interfaces.ts file includes too many changes and may need to be reduced to just relevant changes. 

Added PolicySettings and DeleteModal components for PolicyDetails UI

---

.github/workflows/cypress-workflow.yml
models/interfaces.ts
public/index.ts
public/pages/VisualCreatePolicy/components/States/State.tsx
public/pages/VisualCreatePolicy/containers/CreateAction/CreateAction.tsx
public/pages/VisualCreatePolicy/containers/CreateState/CreateState.tsx
public/pages/VisualCreatePolicy/utils/helpers.test.ts
public/pages/VisualCreatePolicy/utils/helpers.ts
public/plugin.ts

Expose a `registerAction` hook for other plugins to add more Action into ISM UX dynamically.
Having a singleton `actionRepoSingleton` initialized during plugin setup, which will be used for providing UIAction in several places across `CreateState`, `CreateAction`, `State`

Register action hook

---

.github/workflows/cypress-workflow.yml
models/interfaces.ts
public/components/JSONModal/JSONModal.test.tsx
public/components/JSONModal/JSONModal.tsx
public/components/JSONModal/__snapshots__/JSONModal.test.tsx.snap
public/components/JSONModal/index.ts
public/pages/Policies/containers/Policies/Policies.tsx
public/pages/PolicyDetails/components/PolicySettings/PolicySettings.test.tsx
public/pages/PolicyDetails/components/PolicySettings/PolicySettings.tsx
public/pages/PolicyDetails/components/PolicySettings/__snapshots__/PolicySettings.test.tsx.snap
public/pages/PolicyDetails/containers/PolicyDetails/PolicyDetails.tsx
public/pages/VisualCreatePolicy/components/States/State.tsx
public/pages/VisualCreatePolicy/components/States/States.tsx

* Moves ISM templates out of the policy settings panel into it's own panel
* Fixes the edit button always going to edit as JSON, now it shows a modal and lets user choose.
* We were passing in error notification and trying to render as a channel id which crashes the page whenever there is an error notification, now we changed Channel ID -> Error Notification and have a link when it exists that opens up a JSON Modal w/ the error notification JSON
* Fixes a bunch of typescript errors
* Fixes states not actually being read-only on the policy details page by utilizing the passed in isReadOnly prop
* Creates a JSONModal to reuse for policy JSON and error notification JSON
By submitting this pull request, I confirm that my …

Fixes policy details page

---

.github/PULL_REQUEST_TEMPLATE.md
.github/draft-release-notes-config.yml
NOTICE
README.md
opensearch_dashboards.json
package.json
release-notes/opensearch-index-management-dashboards-plugin.release-notes-1.1.0.0.md

Release 1.1.0.0

---

public/pages/PolicyDetails/components/PolicySettings/PolicySettings.tsx
public/pages/PolicyDetails/components/PolicySettings/__snapshots__/PolicySettings.test.tsx.snap
public/pages/PolicyDetails/containers/PolicyDetails/PolicyDetails.tsx
public/pages/VisualCreatePolicy/components/FlyoutFooter/FlyoutFooter.tsx
public/pages/VisualCreatePolicy/components/FlyoutFooter/__snapshots__/FlyoutFooter.test.tsx.snap
public/pages/VisualCreatePolicy/components/ISMTemplates/ISMTemplates.tsx
public/pages/VisualCreatePolicy/components/ISMTemplates/__snapshots__/ISMTemplates.test.tsx.snap
public/pages/VisualCreatePolicy/components/LegacyNotification/LegacyNotification.tsx
public/pages/VisualCreatePolicy/components/LegacyNotification/__snapshots__/LegacyNotification.test.tsx.snap
public/pages/VisualCreatePolicy/components/PolicyInfo/PolicyInfo.tsx
public/pages/VisualCreatePolicy/components/PolicyInfo/__snapshots__/PolicyInfo.test.tsx.snap
public/pages/VisualCreatePolicy/components/TimeoutRetrySettings/TimeoutRetrySettings.tsx
public/pages/VisualCreatePolicy/components/TimeoutRetrySettings/__snapshots__/TimeoutRetrySettings.test.tsx.snap
public/pages/VisualCreatePolicy/components/Transition/Transition.tsx
public/pages/VisualCreatePolicy/components/UIActions/AllocationUIAction.tsx
public/pages/VisualCreatePolicy/components/UIActions/ForceMergeUIAction.tsx
public/pages/VisualCreatePolicy/components/UIActions/IndexPriorityUIAction.tsx
public/pages/VisualCreatePolicy/components/UIActions/ReplicaCountUIAction.tsx
public/pages/VisualCreatePolicy/components/UIActions/RolloverUIAction.tsx
public/pages/VisualCreatePolicy/components/UIActions/RollupUIAction.tsx
public/pages/VisualCreatePolicy/components/UIActions/SnapshotUIAction.tsx
public/pages/VisualCreatePolicy/containers/CreateAction/CreateAction.tsx
public/pages/VisualCreatePolicy/containers/CreateAction/__snapshots__/CreateAction.test.tsx.snap
public/pages/VisualCreatePolicy/containers/CreateState/CreateState.tsx
public/pages/VisualCreatePolicy/containers/CreateState/__snapshots__/CreateState.test.tsx.snap
public/pages/VisualCreatePolicy/containers/CreateTransition/CreateTransition.tsx
public/pages/VisualCreatePolicy/containers/ErrorNotification/__snapshots__/ErrorNotification.test.tsx.snap
public/pages/VisualCreatePolicy/utils/constants.ts
release-notes/opensearch-index-management-dashboards-plugin.release-notes-1.1.0.0.md

* Moves edit button from the policy settings content panel to the page
* Updates transitions to not include a conditions object by default as the backend throws an error if you pass it an empty conditions object
* Makes all inputs in flyouts full width
* Updates retry help text
* Adds some extra spacing between inputs
* Adds back X icon next to Cancel in state flyout
* Fixes missing punctuation
* Removes default ISM template and increases width of empty prompt message
* Moves action/transition flyout secondary button (cancel) to be next to primary button …

Fixes some small UI touchups/issues for new ISM UI

---

.github/workflows/cypress-workflow.yml
public/pages/CreateRollup/components/ScheduleRolesAndNotifications/ScheduleRolesAndNotifications.tsx
public/pages/CreateRollup/containers/CreateRollupForm/CreateRollupForm.tsx
public/pages/CreateRollup/utils/helpers.ts
public/pages/EditRollup/containers/EditRollup.test.tsx
public/pages/EditRollup/containers/EditRollup.tsx
public/pages/RollupDetails/containers/RollupDetails/RollupDetails.tsx

Signed-off-by: Clay Downs downsrob@amazon.com
Rollup delay values are stored in index management in milliseconds only, but with a time unit in the dashboards plugin. Adds a translation for the millisecond value to the displayed time unit when editing, then converts it back to milliseconds on submission.  Also updates the rollup schedule display to correctly show if the job is continuous or non continuous.
Before:
Displaying in milliseconds for any selected execution delay unit
After:
Converting milliseconds to the correct execution delay unit
After saving the edit of execution delay to 60 minutes, before fix:
Incorrectly storing internally as a delay of 60 ms
After saving the edit, after fix:
The 60 minutes from the edit menu was correctly converted to milliseconds
This is for a non …

Fixes editing rollup delay

---

cypress/integration/rollups_spec.js
public/pages/RollupDetails/containers/RollupDetails/RollupDetails.test.tsx

Signed-off-by: Clay Downs <downsrob@amazon.com>
Fixes the flakey rollup enable and disable test. This test would sometimes fail because it would attempt to click the disable button before the rollup details were received. By waiting for the button to display as enabled, this should no longer fail.
Attempts to fix 'can delete a rollup job' unit test by waiting for a button to load before attempting to click it. The empty waitfor statement only waits for tick in the event loop, see [here](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/no-wait-for-empty-callback.md), and does not enforce that the button is available to click.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/30
By submitting this pull request, I confirm …

Fixes flakey tests

---

public/pages/CreateTransform/components/DefineTransforms/DefineTransforms.tsx

Signed-off-by: Eric Lobdell <lobdelle@amazon.com>
Fixes crash on rendering geo_point fields in Create Transform workflow
Also fixes issue rendering boolean fields, now properly shows true/false
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/91

Fixed Transforms geo_point bug and boolean render

---

cypress/integration/managed_indices_spec.js
cypress/support/commands.js
cypress/support/index.d.ts

After adding the jitter cluster setting to index state management in [this commit](https://github.com/opensearch-project/index-management/commit/ab122799283a58bb3f5c6f6d8576c7ba5875f13b), the ISM dashboards cypress test "managed_indices_spec.js/Managed indices -- can change policies" has been failing the majority of the time. The jitter caused the managed index execution to be delayed, which made the success check timeout.
This PR fixes this failure by disabling the jitter at the start of the cypress tests. …

Disables jitter for managed_indices_spec cypress tests

---

.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml

Updates github test workflow versions to 1.2
Removes unneeded dependency install workflow, which is now handled by OpenSearch and the index-management plugin

Update workflow versions to 1.2, streamline test workflows

---

.github/workflows/dco.yml

Adds developer certificate of origin check to github workflows. The mentioned issue also requires updating the repository's contributing guide, but as the Index Management Dashboards contributing guide simply links to the OpenSearch guide, this is not necessary.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/99

Adds developer certificate of origin check workflow

---

cypress/fixtures/sample_rollover_policy.json
cypress/integration/managed_indices_spec.js
cypress/support/commands.js
cypress/support/index.d.ts

Fixes the retry managed index cypress test that broke as part of some backend changes from previous version. Now, we rely on lack of rollover_alias to have a job enter a failed state and then set the alias and retry it.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/70

Fixes retry failed managed index cypress test

---

public/pages/Rollups/containers/Rollups/Rollups.test.tsx
public/pages/Rollups/containers/Rollups/Rollups.tsx
public/pages/Rollups/containers/Rollups/__snapshots__/Rollups.test.tsx.snap
public/pages/Transforms/containers/Transforms/Transforms.test.tsx

Signed-off-by: Annie Lee <leeyun@amazon.com>
Adding a refresh button to rollup landing page
N/A

Add refresh button to rollup page

---

.github/workflows/cypress-workflow.yml
cypress/fixtures/sample_rollover_policy.json
opensearch_dashboards.json
package.json
public/pages/VisualCreatePolicy/containers/CreateState/CreateState.tsx
public/pages/VisualCreatePolicy/containers/VisualCreatePolicy/VisualCreatePolicy.tsx
public/pages/VisualCreatePolicy/utils/helpers.test.ts
public/pages/VisualCreatePolicy/utils/helpers.ts

Changing the state name of the default state wasn't also changing the policy.default_state value (unless it was the one and only state).
This fixes it so that if we have made changes to the state that is currently the default state then we update the default state to the value of the state name.
Also fixes some react state being set after the visual editor page has unmounted.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/139
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin …

Fixes default state not updating when changing state name

---

cypress/integration/transforms_spec.js
public/pages/CreateTransform/components/ReviewSchedule/ReviewSchedule.tsx
public/pages/CreateTransform/components/Schedule/Schedule.tsx
public/pages/CreateTransform/containers/CreateTransformForm/CreateTransformForm.tsx
public/pages/CreateTransform/containers/ReviewAndCreateStep/ReviewAndCreateStep.tsx
public/pages/CreateTransform/containers/SpecifyScheduleStep/SpecifyScheduleStep.tsx
public/pages/Transforms/containers/Transforms/TransformDetails.tsx
public/pages/Transforms/containers/Transforms/Transforms.tsx
public/pages/Transforms/containers/Transforms/__snapshots__/Transforms.test.tsx.snap
public/pages/Transforms/utils/metadataHelper.tsx
release-notes/opensearch-index-management-dashboards-plugin.release-notes-1.3.0.0.md

This change adds support for the continuous mode for transforms in the front end, following the backend introduction in this PR https://github.com/opensearch-project/index-management/pull/206
The changes consist of:
- Adding a radio button to set the continuous mode for transforms
- Displays the continuous mode when confirming the transform details before issuing the final create
- Displays the continuous mode of transforms in the transform details page
- Displays the continuous mode of transforms in the transforms job page
- Separates init and started status for transforms. Previously transforms would show as initializing until they finished, now they show as started when running in continuous mode. …

Adds support for creating and displaying the transform continuous mode

---

models/interfaces.ts
public/pages/VisualCreatePolicy/components/Transition/Transition.tsx
public/pages/VisualCreatePolicy/components/UIActions/RolloverUIAction.tsx
public/pages/VisualCreatePolicy/containers/CreateAction/__snapshots__/CreateAction.test.tsx.snap
public/pages/VisualCreatePolicy/containers/CreateTransition/__snapshots__/CreateTransition.test.tsx.snap
public/pages/VisualCreatePolicy/utils/constants.ts
public/pages/VisualCreatePolicy/utils/helpers.ts

Adds support on UI for min primary shard size rollover condition and min rollover age transition condition
Updates jest snapshot tests
Removes validation for rollover action that was requiring on the UI at least one condition since backend supports no conditions.
Removes the empty rollover conditions in the default rollover action as it was causing it to be sent to backend which was then failing.
Backend PRs:
https://github.com/opensearch-project/index-management/pull/220
https://github.com/opensearch-project/index-management/pull/215
Seems like the visual part just has jest snapshot tests w/ and not functional tests. I see we have [this](https://github.com/opensearch-project/index-management-dashboards-plugin/issues/126) issue to add some cypress ones, but would also be good to have some …

Adds support on UI for min primary shard size rollover condition and min rollover age transition condition

---

.github/workflows/cypress-workflow.yml

Modifies the cypress workflow to no longer use local dependencies.
This code was removed in this PR https://github.com/opensearch-project/index-management-dashboards-plugin/pull/87 and reverted in this PR https://github.com/opensearch-project/index-management-dashboards-plugin/pull/89. I am not sure why this was necessary to revert on 1.x, but the current convention is to ditch local dependencies in favor of snapshots.
NA
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certific …

Removes local dependencies from cypress workflow

---

.github/workflows/backport.yml
.github/workflows/delete_backport_branch.yml
DEVELOPER_GUIDE.md
cypress/integration/transforms_spec.js
models/interfaces.ts
public/pages/CreateTransform/components/ReviewSchedule/ReviewSchedule.tsx
public/pages/CreateTransform/components/Schedule/Schedule.tsx
public/pages/CreateTransform/containers/CreateTransformForm/CreateTransformForm.tsx
public/pages/CreateTransform/containers/ReviewAndCreateStep/ReviewAndCreateStep.tsx
public/pages/CreateTransform/containers/SpecifyScheduleStep/SpecifyScheduleStep.tsx
public/pages/Transforms/containers/Transforms/TransformDetails.tsx
public/pages/Transforms/containers/Transforms/Transforms.tsx
public/pages/Transforms/containers/Transforms/__snapshots__/Transforms.test.tsx.snap
public/pages/Transforms/utils/metadataHelper.tsx
public/pages/VisualCreatePolicy/components/Transition/Transition.tsx
public/pages/VisualCreatePolicy/components/UIActions/RolloverUIAction.tsx
public/pages/VisualCreatePolicy/containers/CreateAction/__snapshots__/CreateAction.test.tsx.snap
public/pages/VisualCreatePolicy/containers/CreateTransition/__snapshots__/CreateTransition.test.tsx.snap
public/pages/VisualCreatePolicy/utils/constants.ts
public/pages/VisualCreatePolicy/utils/helpers.ts
release-notes/opensearch-index-management-dashboards-plugin.release-notes-1.3.0.0.md

Backports all of the missing commits from main to 1.x. Confirmed with `git diff backport-main-1x..main` that all diffs following this backport are limited to the workflow files, as the 1.x workflow files include the 1.x branches and main does not.
N/A

Backports commits from main to 1.x

---

models/interfaces.ts
public/pages/VisualCreatePolicy/components/EuiFormCustomLabel/EuiFormCustomLabel.tsx
public/pages/VisualCreatePolicy/components/UIActions/ShrinkUIAction.tsx
public/pages/VisualCreatePolicy/components/UIActions/index.ts
public/pages/VisualCreatePolicy/containers/CreateAction/__snapshots__/CreateAction.test.tsx.snap
public/pages/VisualCreatePolicy/utils/constants.ts
public/pages/VisualCreatePolicy/utils/helpers.test.ts
public/pages/VisualCreatePolicy/utils/helpers.ts
server/utils/helpers.ts

Signed-off-by: Clay Downs <downsrob@amazon.com>
Adds UI for the shrink action. This PR does not contain any tests, which should be added later. Additional validation should also be added, such as not allowing percentage to shrink shards to input out of the range of 0 to 1. This is currently validated by the backend but additional validation up front would improve the user experience.
If any of the above errors are present, it will not be possible to add the action.
https://github.com/opensearch-project/index-management/issues/40 …

Adds UI for shrink action

---

models/interfaces.ts
public/pages/CreateRollup/utils/helpers.ts
public/pages/CreateTransform/components/DefineTransforms/DefineTransforms.tsx
public/pages/CreateTransform/utils/helpers.ts

Signed-off-by: Ravi Thaluru <thalurur@users.noreply.github.com>
Fix geopoint rendering issue
Earlier if geopoint data type is selected in opensearch sample flight data for example when geopoint data type e.g `DestLocation` is selected then whole page crashes
After fix the geopoint is rendered as a string
render alias fields correctly
Rendering sparse data correctly
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/141
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/134 …

Fix rendering in transforms UI

---

.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml
opensearch_dashboards.json
package.json

Backport of https://github.com/opensearch-project/index-management-dashboards-plugin/pull/192 to remove the rc1 version qualifier from the 2.0 branch. The backport workflow failed me as I merged while the workflow was in progress.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/190

Removes rc1 version qualifier [BACKPORT]

---

public/pages/CreateTransform/components/DefineTransforms/DefineTransforms.tsx

Signed-off-by: Ravi Thaluru <thalurur@users.noreply.github.com>
Few of the transforms UI rendering was bugfixes were fixed in this [PR](https://github.com/opensearch-project/index-management-dashboards-plugin/pull/179/commits) 
As part of above PR I have included `path` field in `FieldItem` datatype which is populated using the mappings data of the index. But when we render the table we use `columns` object data. At the moment the `path` field is none in the columns and as a result will fail to render the alias data type.
This PR fixes the issue by populating path field in columns object using FieldItem
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/141
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/134
By submitting this …

Fix transforms UI for supporting rendering of alias fields

---

public/pages/Repositories/containers/Repositories/Repositories.tsx
public/pages/SnapshotPolicies/containers/SnapshotPolicies/SnapshotPolicies.tsx
public/pages/SnapshotPolicyDetails/containers/SnapshotPolicyDetails/SnapshotPolicyDetails.tsx
public/pages/Snapshots/components/SnapshotFlyout/SnapshotFlyout.tsx
public/pages/Snapshots/containers/Snapshots/Snapshots.tsx

Tune the column width, fix the problem of showing snapshot failures

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json
release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.2.0.0.md
yarn.lock

1. Bumping `2.x` branch from version `2.1` to `2.2`.
2. Bumped `terser` version to `4.8.1` to address this [CVE](https://github.com/opensearch-project/index-management-dashboards-plugin/security/dependabot/10).
3. Drafted `2.2` release notes.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/217

Bumping 2.x branch from version 2.1 to 2.2.

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.2.0.0.md

Added to 2.2 release notes.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/217

Added to 2.2 release notes.

---

.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml
README.md
opensearch_dashboards.json
package.json
release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.2.0.0.md
test/setup.jest.ts
yarn.lock

1. Cherry-picked `2.1` to `2.2` version bump commit.
2. Cherry-picked `terser` version bump commit to address dependabot alert.
3. Cherry-picked release notes commit.
4. Enabled unit and cypress test workflows on all PRs.
5. Adjusted OSD version used by unit and cypress tests to align with OSD branching strategy.
6. Updated a website link in the `README` file that was broken when ODFE was deprecated.
7. Adjusted path for a dependency used by unit tests to align with migration from `EUI` to `OUI`.
Will be closing https://github.com/opensearch-project/index-management-dashboards-plugin/pull/224 in favor of this PR.
For more information on …

Bumping main to 2.2, address dependabot alert, enable test workflows on all PRs, fix snapshot tests.

---

package.json
yarn.lock

Signed-off-by: AWSHurneyt <hurneyt@amazon.com>
Bumped `moment` version to resolve this [dependabot alert](https://github.com/opensearch-project/index-management-dashboards-plugin/security/dependabot/11).

Bumped moment version to resolve dependabot alert.

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Manual backport of https://github.com/opensearch-project/index-management-dashboards-plugin/pull/235.
Closing https://github.com/opensearch-project/index-management-dashboards-plugin/pull/237 and https://github.com/opensearch-project/index-management-dashboards-plugin/pull/238 in favor of this PR.

[Backport 2.x] Version increment 2.2.1

---

cypress/integration/rollups_spec.js
public/components/ContentPanel/ContentPanel.tsx
public/components/ContentPanel/__snapshots__/ContentPanel.test.tsx.snap
public/pages/ChangePolicy/components/ChangeManagedIndices/__snapshots__/ChangeManagedIndices.test.tsx.snap
public/pages/ChangePolicy/components/NewPolicy/__snapshots__/NewPolicy.test.tsx.snap
public/pages/ChangePolicy/containers/ChangePolicy/__snapshots__/ChangePolicy.test.tsx.snap
public/pages/CreatePolicy/components/ConfigurePolicy/__snapshots__/ConfigurePolicy.test.tsx.snap
public/pages/CreatePolicy/components/DefinePolicy/__snapshots__/DefinePolicy.test.tsx.snap
public/pages/CreatePolicy/containers/CreatePolicy/__snapshots__/CreatePolicy.test.tsx.snap
public/pages/CreateRollup/containers/CreateRollupForm/__snapshots__/CreateRollupForm.test.tsx.snap
public/pages/CreateTransform/containers/CreateTransformForm/__snapshots__/CreateTransformForm.test.tsx.snap
public/pages/EditRollup/containers/__snapshots__/EditRollup.test.tsx.snap
public/pages/Indices/containers/Indices/__snapshots__/Indices.test.tsx.snap
public/pages/Main/Main.tsx
public/pages/ManagedIndices/containers/ManagedIndices/__snapshots__/ManagedIndices.test.tsx.snap
public/pages/Policies/containers/Policies/__snapshots__/Policies.test.tsx.snap
public/pages/PolicyDetails/components/PolicySettings/__snapshots__/PolicySettings.test.tsx.snap
public/pages/Snapshots/containers/Snapshots/Snapshots.tsx
public/pages/Transforms/containers/Transforms/__snapshots__/EditTransform.test.tsx.snap
public/pages/VisualCreatePolicy/components/ISMTemplates/__snapshots__/ISMTemplates.test.tsx.snap
public/pages/VisualCreatePolicy/components/PolicyInfo/__snapshots__/PolicyInfo.test.tsx.snap
public/pages/VisualCreatePolicy/components/States/__snapshots__/States.test.tsx.snap
public/pages/VisualCreatePolicy/containers/ErrorNotification/__snapshots__/ErrorNotification.test.tsx.snap

This was done to maintain consistent positioning across Index
Management panels and Snapshot Management panels. Also did the same
for Transform Jobs panel. Signed-off-by: Chris Hesterman
<phestech@amazon.com>
Provides visually consistent positioning of Index Management  and Snapshot Management panels.

Change alignment of Snapshot Management panels in pages/Main/Main.tsx

---

public/utils/constants.ts

Removed the extra forward slash leading to a non-existing documentation page for snapshot management
Signed-off-by: Victor Nilsson <victor.nilsson@etraveligroup.com>
Simple change to remove the extra forward slash in the URL for snapshot management. Described in issue [226](https://github.com/opensearch-project/index-management-dashboards-plugin/issues/226).
[226](https://github.com/opensearch-project/index-management-dashboards-plugin/issues/226)

Remove extra forward slash for URL to snapshot management docs

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.3.0.0.md

Added release notes for 2.3

---

cypress/integration/create_index.js
cypress/support/commands.js
cypress/support/index.d.ts
models/interfaces.ts
public/pages/CreateIndex/components/AliasSelect/AliasSelect.test.tsx
public/pages/CreateIndex/components/IndexDetail/IndexDetail.test.tsx
public/pages/CreateIndex/components/IndexDetail/IndexDetail.tsx
public/pages/CreateIndex/containers/CreateIndex/CreateIndex.tsx
public/pages/Indices/components/IndexDetail/index.tsx

1. By leveraging the API of https://www.elastic.co/guide/en/elasticsearch/reference/7.10/indices-simulate-index.html to copy settings/mappings from v2 template.

feat: enable inheritting from template function when creating index

---

cypress/integration/create_index.js
cypress/integration/split_index.js
public/components/EuiToolTipWrapper/EuiToolTipWrapper.test.tsx
public/components/EuiToolTipWrapper/__snapshots__/EuiToolTipWrapper.test.tsx.snap
public/components/EuiToolTipWrapper/index.tsx
public/components/FormGenerator/__snapshots__/FormGenerator.test.tsx.snap
public/components/FormGenerator/built_in_components/index.tsx
public/containers/IndexDetail/index.tsx
public/pages/CreateIndex/components/IndexDetail/IndexDetail.tsx
public/pages/CreateIndex/components/IndexDetail/__snapshots__/IndexDetail.test.tsx.snap
public/pages/CreateIndex/components/IndexMapping/IndexMapping.tsx
public/pages/CreateIndex/components/IndexMapping/__snapshots__/IndexMapping.test.tsx.snap
public/pages/CreateIndex/containers/CreateIndex/CreateIndex.test.tsx
public/pages/CreateIndex/containers/CreateIndex/CreateIndex.tsx
public/pages/CreateIndex/containers/IndexForm/IndexForm.test.tsx
public/pages/CreateIndex/containers/IndexForm/index.tsx
public/pages/Indices/components/ShrinkIndexFlyout/__snapshots__/ShrinkIndexFlyout.test.tsx.snap
public/pages/Indices/components/SplitIndexFlyout/__snapshots__/SplitIndexFlyout.test.tsx.snap
public/pages/Indices/containers/IndexDetail/IndexDetail.test.tsx
public/pages/Indices/containers/IndexDetail/index.tsx
public/pages/Indices/containers/Indices/Indices.tsx
public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx
public/pages/Indices/containers/IndicesActions/index.tsx
public/pages/Indices/utils/constants.tsx
test/mocks/index.ts

1. Fix issues for first spirint demo.
2. Fix selection bug when refresh indices table.
3. Fix the loop refresh bug in IndexDetail components

Refractor for spirint1

---

cypress/integration/reindex_spec.js
public/pages/CreateIndex/components/IndexDetail/IndexDetail.tsx
public/pages/Reindex/components/CreateIndexFlyout/CreateIndexFlyout.test.tsx
public/pages/Reindex/container/Reindex/Reindex.test.tsx
public/pages/Reindex/container/Reindex/Reindex.tsx
public/pages/Reindex/container/Reindex/__snapshots__/Reindex.test.tsx.snap
public/pages/Reindex/models/interfaces.ts
public/services/IndexService.test.ts
server/services/AliasServices.ts

1. add integration test for create new index in reindex flow
2. add more unit test
3. add writing index check for alias

Add more test case for reindex

---

cypress/integration/indices_spec.js
public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.test.tsx
public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.tsx
public/pages/Indices/components/ShrinkIndexFlyout/__snapshots__/ShrinkIndexFlyout.test.tsx.snap
public/pages/Indices/components/ShrinkIndexFlyout/constants.ts
public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx
public/pages/Indices/containers/IndicesActions/index.tsx

Signed-off-by: Binlong Gao <gbinlong@amazon.com>
1. Add open index button to the Shrink index flyout.
2. Add aliases input form to the Shrink index flyout.
3. Add more test cases.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/397

add open index button & aliases to ShrinkIndexFlyout

---

cypress/integration/split_index.js

Signed-off-by: Xuesong Luo <lxuesong@amazon.com>
[Fix a bug caused by wrong element name in split_index.js]

Fix a bug caused by wrong element name in function test

---

public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx
public/pages/Indices/containers/IndicesActions/__snapshots__/IndicesActions.test.tsx.snap
public/pages/Indices/containers/IndicesActions/index.tsx

Signed-off-by: Binlong Gao <gbinlong@amazon.com>
1. Disable shrink item in the index operation's menu list if a `data_stream` is selected.
2. Add some unit tests.

Disable shrink action if a data_stream is selected in indices page

---

public/pages/Indices/components/CloseIndexModal/CloseIndexModal.test.tsx
public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx
public/pages/Indices/components/CloseIndexModal/__snapshots__/CloseIndexModal.test.tsx.snap
public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.test.tsx
public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.tsx
public/pages/Indices/components/ShrinkIndexFlyout/__snapshots__/ShrinkIndexFlyout.test.tsx.snap

Signed-off-by: Binlong Gao <gbinlong@amazon.com>
1. Fix bug for shrink index operation, shown `set write block` button when the source index' `index.blocks.write` setting is `false`.
2. Show warning when one or more system indices are selected to do close operation.
3. Add more unit tests for the change.
#450 

Fix bug for shrink&close operation

---

public/pages/Indices/components/SplitIndexFlyout/SplitIndexFlyout.test.tsx
public/pages/Indices/components/SplitIndexFlyout/SplitIndexFlyout.tsx
public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx

[Remove unnecessary logic when calculating split shard options. Fix warning in UT;]
[[List any issues this PR will resolve](https://github.com/opensearch-project/index-management-dashboards-plugin/issues/444)]

Index Split: Code cleanup

---

public/pages/CreateIndex/components/IndexDetail/IndexDetail.tsx
public/pages/Reindex/components/ReindexAdvancedOptions/ReindexAdvancedOptions.tsx
public/pages/Reindex/components/ReindexAdvancedOptions/__snapshots__/ReindexAdvancedOptions.test.tsx.snap
public/pages/Reindex/container/Reindex/Reindex.tsx
public/pages/Reindex/container/Reindex/__snapshots__/Reindex.test.tsx.snap

enable full width for query expression JSON editor

enable fullwidth for JSON editor

---

cypress/integration/indices_spec.js
public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx
public/pages/Indices/components/CloseIndexModal/__snapshots__/CloseIndexModal.test.tsx.snap
public/pages/Main/Main.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.test.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/__snapshots__/ShrinkIndex.test.tsx.snap
public/pages/ShrinkIndex/container/ShrinkIndex/index.ts
public/pages/ShrinkIndex/index.ts
public/pages/ShrinkIndex/utils/constants.ts

1. Add shrink index page.
2. Add unit tests for the change.
3. Fix some bug.

Add shrink index page

---

public/pages/Indices/utils/helpers.ts
public/pages/SplitIndex/components/SplitIndexForm/SplitIndexForm.tsx
public/pages/SplitIndex/container/SplitIndex/SplitIndex.tsx
public/pages/SplitIndex/container/SplitIndex/__snapshots__/SplitIndex.test.tsx.snap

Signed-off-by: Xuesong Luo <lxuesong@amazon.com>
[Minor wording change after review]

Minor wording change after review

---

public/pages/Reindex/components/ReindexAdvancedOptions/ReindexAdvancedOptions.test.tsx
public/pages/Reindex/components/ReindexAdvancedOptions/ReindexAdvancedOptions.tsx
public/pages/Reindex/components/ReindexAdvancedOptions/__snapshots__/ReindexAdvancedOptions.test.tsx.snap
public/pages/Reindex/container/Reindex/Reindex.tsx
public/pages/Reindex/container/Reindex/__snapshots__/Reindex.test.tsx.snap

support reindex unique documents

---

public/pages/Reindex/components/ReindexAdvancedOptions/ReindexAdvancedOptions.tsx
public/pages/Reindex/components/ReindexAdvancedOptions/__snapshots__/ReindexAdvancedOptions.test.tsx.snap

Wording change for reindex page
N/A

Reindex page wording change

---

public/pages/Reindex/container/Reindex/Reindex.tsx
public/pages/Reindex/models/interfaces.ts

Remove unused TODO, the logic already included in `IndexSelect` component.

Remove unused TODO

---

public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/__snapshots__/ShrinkIndex.test.tsx.snap

Signed-off-by: gaobinlong <gbinlong@amazon.com>
Add a space before the learn more link in shrink index page.

Add a space before the learn more link in shrink index page

---

.github/workflows/cypress-workflow.yml
cypress/integration/create_index.js
public/lib/field/rules/index.ts
public/pages/Aliases/containers/CreateAlias/index.tsx
public/pages/Aliases/containers/DeleteAliasModal/DeleteAliasModal.tsx
public/pages/CreateIndex/components/IndexDetail/IndexDetail.tsx
public/pages/CreateIndex/components/IndexMapping/IndexMapping.tsx
public/pages/CreateIndexTemplate/components/IndexSettings/IndexSettings.tsx
public/pages/CreateIndexTemplate/containers/CreateIndexTemplate/__snapshots__/CreateIndexTemplate.test.tsx.snap
public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.tsx
public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx
public/pages/Indices/components/CloseIndexModal/__snapshots__/CloseIndexModal.test.tsx.snap
public/pages/Indices/components/DeleteIndexModal/DeleteIndexModal.test.tsx
public/pages/Indices/components/DeleteIndexModal/DeleteIndexModal.tsx
public/pages/Indices/components/DeleteIndexModal/__snapshots__/DeleteIndexModal.test.tsx.snap
public/pages/Reindex/components/CreateIndexFlyout/__snapshots__/CreateIndexFlyout.test.tsx.snap

Minor changes for v2.5

---

public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.test.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.tsx

There are some minor changes in the shrink index page:
1. Remove inaccurate pre-check, when a copy of every shard  of the source index do not reside on the same node, then shrink api call will fail, currently we have checked the index settings before users click the shrink button to see whether the source index contains a index setting like `index.routing.allocation.require._*` or not, if not a warning will be shown in the page, but this pre-check is not accurate because if the cluster has only one node or the setting `index.number_of_replicas` of the source index is equal to the number of nodes minus 1 , then users do not need to allocate a copy of every shard to one node, so we'd better remove it.
2. Change some wording in the page, like change `Green` to `green` in the error message. …

Remove inaccurate pre-check in shrink index page

---

.github/workflows/cypress-workflow.yml
.github/workflows/release-workflow.yml
.github/workflows/unit-tests-workflow.yml

The GitHub workflow uses the `engines` from OSD incorrectly. This change fixes that.

 Fix Node.js and Yarn installation in CI

---

cypress/integration/data_streams.js
public/components/DescriptionListHoz/DescriptionListHoz.tsx
public/components/FormGenerator/built_in_components/index.tsx
public/pages/CreateDataStream/components/IndexSettings/IndexSettings.tsx
public/pages/CreateDataStream/containers/BackingIndices/BackingIndices.tsx
public/pages/CreateDataStream/containers/CreateDataStream/__snapshots__/CreateDataStream.test.tsx.snap
public/pages/CreateDataStream/containers/DataStreamDetail/DataStreamDetail.tsx
public/pages/CreateDataStream/containers/DataStreamDetail/__snapshots__/DataStreamDetail.test.tsx.snap
public/pages/CreateDataStream/containers/DefineDataStream/DefineDataStream.tsx
public/pages/CreateDataStream/containers/IndexAlias/IndexAlias.tsx
public/pages/CreateDataStream/containers/TemplateMappings/TemplateMappings.tsx
public/pages/CreateDataStream/hooks.tsx
public/pages/CreateDataStream/interface.ts
public/pages/CreateIndexTemplate/components/DefineTemplate/DefineTemplate.tsx
public/pages/CreateIndexTemplate/components/TemplateType/TemplateType.tsx
public/pages/CreateIndexTemplate/containers/CreateIndexTemplate/CreateIndexTemplate.tsx
public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.test.tsx
public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.tsx
public/pages/CreateIndexTemplate/containers/TemplateDetail/__snapshots__/TemplateDetail.test.tsx.snap
public/pages/DataStreams/containers/DataStreams/DataStreams.tsx
public/pages/DataStreams/containers/DataStreams/__snapshots__/DataStreams.test.tsx.snap
public/pages/DataStreams/containers/DeleteDataStreamsModal/DeleteDataStreamsModal.tsx
public/pages/DataStreams/containers/DeleteDataStreamsModal/__snapshots__/DeleteDataStreamsModal.test.tsx.snap
public/pages/Indices/containers/Indices/__snapshots__/Indices.test.tsx.snap
public/pages/Indices/utils/constants.tsx

* feat: temp commit
* feat: update
* feat: update
* refractor: move index mapping to common components
* feat: enable create data stream
* feat: enable data stream detail
* feat: some typo fix
* feat: enable data stream management
* feat: update
* feat: update
* feat: enable unit test
* feat: add data streams cypress test
* feat: update version
* feat: update
* feat: update
* feat: update
* feat: update
* feat: update
* feat: update
* feat: update
* feat: make cypress run
* feat: update snapshot
* feat: update
* feat: update
* feat: update
* feat: optimize search interaction
* feat: update
* feat: add explanation
* feat: add time field
* feat: update
* feat: copy the properties
* feat: update
* feat: update
* feat: update
* feat: update
* feat: update
* feat: update
* feat: update
* feat: …

[Backport main]Feature: data streams (#605)

---

public/pages/CreateRollup/components/AdvancedAggregation/AdvancedAggregation.tsx

Fix link destination and make the link open in a new window. I clicked the link and because it didn't open in a new window, it ruined my form.
So I decided to try to help prevent anyone else from suffering the same fate by fixing the link.

Update broken link

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Bump version to 2.7.0

---

cypress/integration/plugins/index-management-dashboards-plugin/force_merge.js
public/components/FormGenerator/built_in_components/index.tsx
public/components/IndexDetail/IndexDetail.tsx
public/components/IndexMapping/IndexMapping.tsx
public/pages/Aliases/containers/AliasActions/AliasActions.test.tsx
public/pages/Aliases/containers/AliasActions/index.tsx
public/pages/Aliases/containers/DeleteAliasModal/DeleteAliasModal.tsx
public/pages/CreateComposableTemplate/components/IndexSettings/IndexSettings.tsx
public/pages/CreateIndex/containers/IndexForm/index.tsx
public/pages/CreateIndexTemplate/components/IndexSettings/IndexSettings.tsx
public/pages/CreateIndexTemplate/containers/ComposableTemplate/ComposableTemplate.tsx
public/pages/CreateIndexTemplate/containers/TemplateDetail/__snapshots__/TemplateDetail.test.tsx.snap
public/pages/IndexDetail/containers/IndexDetail/IndexDetail.tsx
release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.7.0.0.md
server/routes/indices.ts
server/services/IndexService.ts

Fix: bugs during internal bugathon and fix the alias deletion issue in security mode.

---

public/pages/CreateDataStream/containers/DataStreamDetail/DataStreamDetail.tsx
public/pages/DataStreams/containers/DataStreams/DataStreams.tsx
public/pages/DataStreams/containers/DataStreamsActions/DataStreamsActions.test.tsx
public/pages/DataStreams/containers/DataStreamsActions/index.tsx

to filter blocked datastreams in DataStreamsActions page, we need to get the DataStream value, not only the name. We need to pass in the DataStream values from DataStreams page

Pass data stream to actions

---

MAINTAINERS.md

Updating the MAINTAINERS file with correct GitHub id

Updating the MAINTAINERS file with correct GitHub id

---

public/utils/helpers.test.ts
public/utils/helpers.ts

Fix the problem when reponse is `undefined`; only filter out red indices in `open status`
see #751 

fix common funcs: status filter, empty response

---

public/utils/helpers.test.ts
public/utils/helpers.ts

* fix common funcs: status filter, empty response
Signed-off-by: zhichao-aws <zhichaog@amazon.com>
* also filter case null and empty string
Signed-off-by: zhichao-aws <zhichaog@amazon.com>
---------
Signed-off-by: zhichao-aws <zhichaog@amazon.com>
(cherry picked from commit 9d4cdd983a5d1212a0006781d3a8cf2125d58b43)

[Backport 2.x] fix common funcs: status filter, empty response

---

.github/workflows/cypress-workflow.yml
release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.8.0.0.md

Fix CI on Node.js v18

---

server/services/CommonService.test.ts
server/services/CommonService.ts

fix: add validation on data.method when using transport.request

---

public/pages/CreateSnapshotPolicy/components/CronSchedule/CronSchedule.tsx
public/pages/Snapshots/components/SnapshotFlyout/SnapshotFlyout.tsx

This PR fixes below issues:
1. Snapshot flyout showing incorrect repository name
2. When editing a snapshot policy, the schedule input gets populated with default values instead of the policy schedule details.
#823 , #822 

Fixed repo name in snapshot flyout; Use schedule from policy during edit

---

.github/workflows/backport.yml

update backport branch name as `branch_name` was deprecated
follow up changes for #821 

update backport branch name

---

babel.config.js

Remove babel override for build and keep it for unit test, based on that add a condition in `babel.config.js` file.
related to #741 

Fix `exports is undefined`

---

public/components/BottomBar/__snapshots__/BottomBar.test.tsx.snap
public/components/UnsavedChangesBottomBar/__snapshots__/UnsavedChangesBottomBar.test.tsx.snap

Update the unit tests

---

cypress/integration/plugins/index-management-dashboards-plugin/policies_spec.js

alias3 gets removed as per instructions from `sample_policy_alias_action.json`. In the final contains verification we do not need to check for alias3.
#911 

fixed alias3 contains error

---

public/pages/ChangePolicy/containers/ChangePolicy/ChangePolicy.tsx
public/pages/ChangePolicy/containers/ChangePolicy/__snapshots__/ChangePolicy.test.tsx.snap

Added Cancel button to `ChangePolicy.tsx`
#840 

adding cancel button to change policy

---

babel.config.js

Seems the babel plugins we used before are deprecated, this PR update them
https://www.npmjs.com/package/@babel/plugin-proposal-class-properties
https://www.npmjs.com/package/@babel/plugin-proposal-object-rest-spread

Update the babel require

---

cypress/integration/plugins/index-management-dashboards-plugin/aliases.js

Solution: 
Intercepting the apiCaller POST call and waiting for the call to complete before moving on to check if the "Rows per page" is present.
The reason for it being flaky is that the `apiCaller` sometimes takes exteremely long time to return data as the number of elements are high and if the network tab is open in `cypress` while the test is being conducted the `API calls` take a very long time.
If the flaky test reoccurs then:
1. Change the number of POST calls in the `before` in `aliases.js`
2. Increase the timeout in the line below:
```bash
cy.wait("@apiCaller", { timeout: 120000 });
```
#910 
For more information on following Developer Certificate of Origin and …

[flaky test]solution for aliases.js 

---

public/pages/CreateDataStream/containers/BackingIndices/BackingIndices.tsx
public/pages/Indices/containers/Indices/__snapshots__/Indices.test.tsx.snap
public/pages/Indices/utils/constants.tsx
server/services/IndexService.ts

Make managed by policy field sortable.
Fix unsupported operation exception error while sorting by Data stream field.
Ascending order
Descending order
List any issues this PR will resolve - [106](https://github.com/opensearch-project/index-management-dashboards-plugin/issues/106) , [948](https://github.com/opensearch-project/index-management-dashboards-plugin/issues/948)

sort by managed policy feature

---

cypress/integration/plugins/index-management-dashboards-plugin/notification_settings.js

Fix the notification_setting test by giving a obedient slack url
regression from https://github.com/opensearch-project/notifications/pull/814

Fix the notification_setting test by giving a obedient slack url

---

package.json
yarn.lock

Update browserify-sign to fix `cve-2023-46234`.
https://github.com/opensearch-project/index-management-dashboards-plugin/security/dependabot/23

Update browserify-sign to fix cve-2023-46234

---

.github/workflows/backport.yml

Backport workflow is failing on 2.x and other versions due to missing condition on PR title. 

.github: update backport to not run on backport PRs

---

cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js

Adding intercepts and wait time to mitigate flaky tests.
#968 

rollups/transform: wait for page to render

---

package.json
yarn.lock

CVE fixes for:- 
CVE-2022-38900
CVE-2021-3807
CVE-2021-43138
CVE-2022-25858
CVE-2022-37603
CVE-2023-26136
CVE-2022-37599
CVE-2022-37601

Fixed CVEs for OS 1.3.15 patch release

---

package.json
yarn.lock

[Backport 2.x]CVE fixes

---

.github/workflows/verify-binary-installation.yml

I have observed some issues within other plugins of issues being only caught at run time. This is because several things can go wrong during the build process, which may not be caught in a dev setup. This adds a workflow to verify that building and installing into OSD works on every PR.
Related issues:
https://github.com/opensearch-project/security-dashboards-plugin/issues/1709
https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/875
https://github.com/opensearch-project/dashboards-observability/pull/309 …

Add workflow to verify binary installation into dashboards core

---

public/containers/ClearCacheModal/ClearCacheModal.tsx
public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx

When none of the indices are selected, ClearCacheModal makes call to `//_cache/clear` path. Here, the intention is to clear the cache for all indices, let's make it explicit by passing `_all` as target.
New call: `/_all/_cache/clear`
N/A

specify _all as target in ClearCacheModal

---

public/pages/Main/Main.tsx

With the latest changes in knowing the default DataSourceId, we are conditionally mounting the Route components.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/1038

Mounting MDS Picker on the empty route

---

public/pages/Main/Main.tsx

DataSourcePicker in core expects activeOption prop to be undefined in the first load, so that it can choose a default data source and send it as part of `onSelectedDataSources` callback function.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/1041
- [✅] Commits are signed per the DCO using --signoff

Bug fix active option

---

DEVELOPER_GUIDE.md

This PR removes the non existing backport file reference and adds latest guidelines for backporting. This will resolve the failing lint checks in existing CIs

Fixed Backport section in developer guide

---

public/pages/Main/Main.tsx

This PR resolves create rollup and transform bug
Resolves #1045

Fixed bug: Readonly DataSourceMenu should be in read only state in create rollup and create transform workflows

---

public/pages/CreateRollup/containers/CreateRollup/CreateRollup.tsx
public/pages/CreateTransform/containers/CreateTransformForm/CreateTransformForm.tsx
public/pages/CreateTransform/containers/SetUpIndicesStep/SetUpIndicesStep.tsx

In Transform job create flows, user is able to select target and source index but indices belong to a particular datsource and needs to be reset on change of datasource. This PR does that
https://github.com/opensearch-project/index-management-dashboards-plugin/assets/20185657/616e90f7-2216-45e6-9829-d8cfad0ce636

Fixed Transform job create flow where indices won't reset after changing datasource

---

cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
cypress/integration/plugins/index-management-dashboards-plugin/data_streams.js
cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js

When testing against cluster with more than one node, we encounter that this check fails as total number of uncommitted operations will be as per replica configuration. Eg. for a 1:1 pri:rep case, total number of uncommitted operations will be two (one for primary, one for replica). Let's change the check to check for inequality instead.
N/A

cypress: modify test to check for inequality

---

opensearch_dashboards.json
public/pages/Main/Main.tsx

Adds changes for version decoupling by passing filter function which utilises manifest file to filter data sources.
N/A

Adding dataVersionFilter support to MDS to enable version decoupling

---

public/pages/Main/Main.tsx
public/plugin.ts
yarn.lock

This PR adds new navigation changes for index-management and snapshot management under data management 
Will takeup the datasourceID persistence across in-app navigation with new navigation change in a followup PR
Related Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7029

New Navigation UX change

---

public/pages/Main/Main.tsx
public/plugin.ts

This change persists dataSourceId across ISM sub applications when new Nav Ux is enabled
Related Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7027

Persist dataSourceId across applications under new Nav change

---

package.json
yarn.lock

Updates yarn.lock
Addresses [CVE-2024-4068](https://github.com/advisories/GHSA-grv7-fg5c-xmjg)
NA

Bumped up braces package version to address CVE-2024-4068

---

public/plugin.ts

This PR try to reuse existing applications into new left navigation so that there won't be duplicated entries for the same page.

[navigation]feat: reuse applications

---

public/pages/CreateDataStream/containers/CreateDataStream/CreateDataStream.test.tsx
public/pages/CreateDataStream/containers/CreateDataStream/CreateDataStream.tsx
public/pages/CreateDataStream/containers/DataStreamDetail/DataStreamDetail.test.tsx
public/pages/CreateDataStream/containers/DataStreamDetail/DataStreamDetail.tsx
public/pages/CreateRollup/containers/CreateRollup/CreateRollup.tsx
public/pages/CreateRollup/containers/CreateRollupForm/CreateRollupForm.test.tsx
public/pages/CreateRollup/containers/CreateRollupForm/CreateRollupForm.tsx
public/pages/CreateRollup/containers/CreateRollupStep2/CreateRollupStep2.tsx
public/pages/CreateRollup/containers/CreateRollupStep3/CreateRollupStep3.tsx
public/pages/CreateRollup/containers/CreateRollupStep4/CreateRollupStep4.tsx
public/pages/DataStreams/components/IndexControls/IndexControls.tsx
public/pages/DataStreams/containers/DataStreams/DataStreams.test.tsx
public/pages/DataStreams/containers/DataStreams/DataStreams.tsx
public/pages/DataStreams/containers/DataStreamsActions/index.tsx
public/pages/EditRollup/containers/EditRollup.test.tsx
public/pages/EditRollup/containers/EditRollup.tsx
public/pages/ForceMerge/container/ForceMerge/ForceMerge.test.tsx
public/pages/ForceMerge/container/ForceMerge/ForceMerge.tsx
public/pages/Rollover/containers/Rollover/Rollover.test.tsx
public/pages/Rollover/containers/Rollover/Rollover.tsx
public/pages/RollupDetails/components/GeneralInformation/GeneralInformation.tsx
public/pages/RollupDetails/containers/RollupDetails/RollupDetails.test.tsx
public/pages/RollupDetails/containers/RollupDetails/RollupDetails.tsx
public/pages/Rollups/containers/Rollups/Rollups.test.tsx
public/pages/Rollups/containers/Rollups/Rollups.tsx

Update new header for datastreams and rollups jobs.
1st half -> ![image](https://github.com/user-attachments/assets/38e6c84d-ecb1-4afa-b3d6-89673c4ba00f)
2nd half -> ![image](https://github.com/user-attachments/assets/4ce61d12-aabc-420e-815b-cbd8e8e0a0f8)

Update new header for datastreams and rollups jobs.

---

public/pages/Main/Main.tsx
public/pages/Notifications/containers/Notifications/Notifications.tsx
server/services/NotificationService.ts

This change adds multi data source selector (described in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6035). This change adds MDS support to Notification page in ISM. 
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/982 This issue will be solved partially through this PR.
- [✅] Commits are signed per the DCO using --signoff

Adding MDS support in Notifications page in ISM

---

public/components/FilterGroup/index.tsx
public/components/IndexMapping/IndexMapping.tsx
public/components/IndexMapping/interfaces.ts
public/pages/ComposableTemplates/components/IndexControls/IndexControls.tsx
public/pages/ComposableTemplates/containers/ComposableTemplates/ComposableTemplates.test.tsx
public/pages/ComposableTemplates/containers/ComposableTemplates/ComposableTemplates.tsx
public/pages/CreateComposableTemplate/containers/CreateComposableTemplate/CreateComposableTemplate.test.tsx
public/pages/CreateComposableTemplate/containers/CreateComposableTemplate/CreateComposableTemplate.tsx
public/pages/CreateComposableTemplate/containers/TemplateDetail/TemplateDetail.test.tsx
public/pages/CreateComposableTemplate/containers/TemplateDetail/TemplateDetail.tsx
public/pages/CreateComposableTemplate/containers/TemplateMappings/TemplateMappings.tsx
public/pages/CreateComposableTemplate/interface.ts
public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.test.tsx
public/plugin.ts

This PR updates the new header for component template pages
List view : 
Create view : 
Detail view : 
List view : 
Create view : 
Detail view :

update newHeader for component template pages

---

public/pages/CreatePolicy/components/DefinePolicy/DefinePolicy.tsx
public/pages/CreatePolicy/containers/CreatePolicy/CreatePolicy.tsx
public/pages/Policies/containers/Policies/Policies.tsx
public/pages/VisualCreatePolicy/components/ChannelNotification/ChannelNotification.tsx
public/pages/VisualCreatePolicy/components/FlyoutFooter/FlyoutFooter.tsx
public/pages/VisualCreatePolicy/components/ISMTemplate/ISMTemplate.tsx
public/pages/VisualCreatePolicy/components/ISMTemplates/ISMTemplates.tsx
public/pages/VisualCreatePolicy/components/States/States.tsx
public/pages/VisualCreatePolicy/components/Transition/Transition.tsx
public/pages/VisualCreatePolicy/containers/CreateAction/CreateAction.tsx
public/pages/VisualCreatePolicy/containers/CreateState/Actions.tsx
public/pages/VisualCreatePolicy/containers/CreateState/CreateState.tsx
public/pages/VisualCreatePolicy/containers/CreateState/Transitions.tsx
public/pages/VisualCreatePolicy/containers/CreateTransition/CreateTransition.tsx
public/pages/VisualCreatePolicy/containers/ErrorNotification/ErrorNotification.tsx
public/pages/VisualCreatePolicy/containers/VisualCreatePolicy/VisualCreatePolicy.tsx

This PR is followup for [PR](https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1108). Making few look and feel good changes. For making buttons size small & bars compressed.
Few changes in Create Index State management pages : 
OldUi : 
NewUi : 
OldUi:
NewUi:

Making Look and Feel Changes in ISM pages

---

public/pages/CreateSnapshotPolicy/containers/CreateSnapshotPolicy/CreateSnapshotPolicy.tsx
public/pages/DataStreams/containers/DataStreams/DataStreams.tsx
public/pages/SnapshotPolicies/containers/SnapshotPolicies/SnapshotPolicies.tsx

This PR fixes some import issues that went with https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1132 in datastream.tsx and Snapshotpolicies pages.

Fixes import issues in DataStreams and Snapshot policies

---

public/pages/Repositories/containers/Repositories/Repositories.tsx

In the current implementation with this https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1103 change. We replaced all instances of EuiButtons to EuiSmallButton where explicitly size is not set. With this change we have removed the EuiButton import from the pages and that caused an issue for Snapshot Repositores page to render. In this PR i've changed the EuiButton instance to EuiSmallButton. 

Replace EuiButton to EuiSmallButton in repositories page

---

public/pages/Aliases/components/IndexControls/IndexControls.tsx
public/pages/ChangePolicy/components/ChangeManagedIndices/ChangeManagedIndices.tsx
public/pages/ChangePolicy/components/ChangeManagedIndices/__snapshots__/ChangeManagedIndices.test.tsx.snap
public/pages/ChangePolicy/components/NewPolicy/NewPolicy.tsx
public/pages/ChangePolicy/components/NewPolicy/__snapshots__/NewPolicy.test.tsx.snap
public/pages/ChangePolicy/containers/ChangePolicy/ChangePolicy.tsx
public/pages/ChangePolicy/containers/ChangePolicy/__snapshots__/ChangePolicy.test.tsx.snap
public/pages/ComposableTemplates/components/IndexControls/IndexControls.tsx
public/pages/ComposableTemplates/containers/ComposableTemplates/ComposableTemplates.tsx
public/pages/CreateTransform/containers/ReviewAndCreateStep/ReviewAndCreateStep.tsx
public/pages/Indices/components/IndexControls/IndexControls.tsx
public/pages/Indices/containers/Indices/Indices.tsx
public/pages/Main/Main.tsx
public/pages/ManagedIndices/components/ManagedIndexControls/ManagedIndexControls.tsx
public/pages/ManagedIndices/containers/ManagedIndices/ManagedIndices.tsx
public/pages/Reindex/container/Reindex/Reindex.test.tsx
public/pages/Reindex/container/Reindex/Reindex.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.test.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.tsx
public/pages/SplitIndex/container/SplitIndex/SplitIndex.test.tsx
public/pages/SplitIndex/container/SplitIndex/SplitIndex.tsx
public/pages/Templates/components/IndexControls/IndexControls.tsx
public/pages/Templates/containers/Templates/Templates.tsx
public/pages/Transforms/containers/Transforms/TransformDetails.tsx
public/pages/Transforms/containers/Transforms/Transforms.tsx
public/pages/Transforms/utils/metadataHelper.tsx
test/helper.ts
yarn.lock

Backport ccdfcd3fbb37a30e3f6afde0243b0d15ff2de7b5 from #1141 
There were conflicts in yarn.lock file. Resolved those by accepting all incoming changes 

[Backport-2.x] Bug fixes and retracting some formatting changes (#1141)

---

public/pages/Indices/components/NotificationModal/NotificationModal.tsx
public/pages/Indices/components/NotificationModal/UnsavedChangesButton.tsx
public/pages/Indices/components/NotificationModal/index.ts
public/pages/Indices/containers/Indices/Indices.tsx

This will get merged only after https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1141 as its a dependent PR

Add Notification Modal on Indices page

---

.github/CODEOWNERS
MAINTAINERS.md

In https://github.com/opensearch-project/index-management/issues/1230 I asked ISM maintainers whether they are actively maintaining the plugin. Many also said they are not maintaining the dashboards plugin. Moved them to emeritus.
If any of the remaining folks @bowenlan-amzn @Hailong-am @RamakrishnaChilaka @vikasvb90 @SuZhou-Joe need to move please lmk!
It also looks like the addition of @RamakrishnaChilaka didn't include an update to CODEOWNERS and permissions were not adjusted. I can take care of it after this is merged. …

Updated active maintainers.

---

public/pages/CreateSnapshotPolicy/components/SnapshotIndicesRepoInput/SnapshotIndicesRepoInput.tsx
public/pages/CreateSnapshotPolicy/containers/CreateSnapshotPolicy/CreateSnapshotPolicy.tsx
public/pages/Reindex/components/CreateIndexFlyout/__snapshots__/CreateIndexFlyout.test.tsx.snap
public/pages/Repositories/components/CreateRepositoryFlyout/CreateRepositoryFlyout.tsx
public/pages/Repositories/containers/Repositories/Repositories.tsx
public/pages/SnapshotPolicies/containers/SnapshotPolicies/SnapshotPolicies.tsx
public/pages/Snapshots/containers/Snapshots/Snapshots.tsx
public/pages/VisualCreatePolicy/components/FlyoutFooter/FlyoutFooter.tsx
public/pages/VisualCreatePolicy/components/FlyoutFooter/__snapshots__/FlyoutFooter.test.tsx.snap

**Note that this PR only contains partial changes, and the other changes are made in https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1157**
This PR makes consistency and density improvements, including:
1. Using small font size as normal paragraph font size through 
2. Using semantic headers (H1s on main pages, H2s on modals/flyouts) wrapped under
3. Using Plus icons for create use cases and PlusInCricle icon for add use cases.
|     Before        |       After        |
| ------------- | ------------- |
| <img width="300" alt="Screenshot 2024-08-28 at 8 13 50 PM" src="https://github.com/user-attachments/assets/257cd0f5-3ebf-441a-bd80-375daf5b3af1">  | <img width="300" alt="Screenshot 2024-08-28 at 8 14 29 PM" …

[Look & Feel] Consistency and Density Changes for Snapshot Management

---

public/pages/Reindex/components/CreateIndexFlyout/__snapshots__/CreateIndexFlyout.test.tsx.snap
public/pages/Rollups/containers/Rollups/Rollups.tsx
public/pages/Transforms/containers/Transforms/Transforms.tsx
public/pages/VisualCreatePolicy/components/FlyoutFooter/FlyoutFooter.tsx
public/pages/VisualCreatePolicy/components/FlyoutFooter/__snapshots__/FlyoutFooter.test.tsx.snap

This PR achieves 3 things. 
1. Show number of rollup jobs in the title of rollup jobs
2. Show number of transform jobs in the title of transform jobs
3. Removes plus in circle icon in snapshot pages buttons introduced by https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1148 as this is not required according to guidelines.
Rollup Jobs
Transform Jobs
Rollup Jobs
Transform Jobs

Update rollup jobs and transform jobs title with total numbers of jobs

---

.github/workflows/cypress-workflow.yml
public/pages/CreateIndexTemplate/containers/CreateIndexTemplate/__snapshots__/CreateIndexTemplate.test.tsx.snap
public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.tsx
public/pages/IndexDetail/containers/IndexDetail/IndexDetail.tsx
public/pages/Indices/components/IndexControls/IndexControls.tsx
public/pages/Indices/components/NotificationModal/NotificationModal.tsx
public/pages/Indices/components/NotificationModal/UnsavedChangesButton.tsx
public/pages/Indices/containers/Indices/Indices.tsx
public/pages/ManagedIndices/components/ManagedIndexControls/ManagedIndexControls.tsx
public/pages/ManagedIndices/containers/ManagedIndices/ManagedIndices.tsx
public/pages/ManagedIndices/containers/ManagedIndices/__snapshots__/ManagedIndices.test.tsx.snap
public/pages/Notifications/containers/Notifications/Notifications.tsx
public/pages/Policies/containers/Policies/Policies.tsx
public/pages/Policies/containers/Policies/__snapshots__/Policies.test.tsx.snap
public/pages/Repositories/containers/Repositories/Repositories.tsx
public/pages/Rollups/containers/Rollups/Rollups.tsx
public/pages/SnapshotPolicies/containers/SnapshotPolicies/SnapshotPolicies.tsx
public/pages/Snapshots/components/RestoreActivitiesPanel/RestoreActivitiesPanel.tsx
public/pages/Snapshots/containers/Snapshots/Snapshots.tsx
public/pages/Transforms/components/TransformEmptyPrompt/TransformEmptyPrompt.tsx
public/pages/Transforms/containers/Transforms/Transforms.tsx

Fixed some Fit and Finish UX changes along with couple of other fixes: 
- Added refresh button in transform jobs page
- Fixed refresh button in indexes and policy managed indices page
Notifications Modal:
Refresh Button toolkit:
Removed extra spacing between checkbox and policy column
Spacing between the tabs and content set to medium

Fit and Finish UX changes

---

.github/actions/run-cypress-tests/action.yaml
.github/workflows/cypress-with-security-workflow.yml
.github/workflows/cypress-workflow.yml

This PR is a small follow-up to https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1202 to simplify the action and remove an unnecessary env variable. Instead of getting the version from this variable, it will get it from the branch-specific build.gradle file and spin up a `<Version>-SNAPSHOT` version of a node for testing. 

Remove unecessary OPENSEARCH_VERSION from cypress test run

---

public/pages/Snapshots/components/RestoreSnapshotFlyout/RestoreSnapshotFlyout.tsx

Previously restoring a snapshot always tries to restore index alias even if the restore alias is unchecked from the dashboard.
This bug is now being fixed with this PR as we set the checkbox for restore alias as false default option and add a toggle check when users chooses to select alias restore option.  

bug-fix: Restore snapshot shouldn't restore index alias always

---

public/pages/CreateSnapshotPolicy/components/CronSchedule/CronSchedule.tsx
public/pages/CreateSnapshotPolicy/containers/CreateSnapshotPolicy/CreateSnapshotPolicy.tsx

This pull request addresses two significant bugs in the snapshot policy functionality:
**Schedule Editing Bug:**
Fixed an issue where users were unable to modify the snapshot schedule time during policy editing.
Users can now successfully update the snapshot timing as needed.
**Index Expression Display Bug:**
Resolved a problem where entered index expressions were not displaying correctly, and no snapshots were happening for that policy with correct indices. 
The snapshot details page now properly shows the index expressions as strings, replacing the previous [Object][Object] display. Snapshot's are taking place with correct indices. 
This fix ensures that users can accurately view and verify their index selections.
Testing:
Verified that snapshot schedule times can be edited and saved …

Bug Fixes in Snapshot Policy: Schedule Editing and Index Expression Display

---

public/pages/Snapshots/components/RestoreSnapshotFlyout/RestoreSnapshotFlyout.tsx

This PR is follow up PR https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1193  for fixing the bug in snapshot restore page. Currently snapshot restore always restores index alias. 
In this PR we set default value to `true` for include_aliases parameter as mentioned in the documentation: https://opensearch.org/docs/latest/api-reference/snapshots/restore-snapshot/#request-body-fields which we changed in the previous PR by mistake. 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin …

bug fix: Snapshot restore always restores index alias

---

.github/CODEOWNERS
MAINTAINERS.md

Updating the maintainers and codeowners list

Updating the maintainers and codeowners list

---

.github/CODEOWNERS

Adding new maintainers as CodeOwners also

Adding new maintainers as Codeowners also

---

.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml

sticky to ubuntu version 22.04 as ubuntu-latest will start to use 24.04 mentioned [here](https://github.com/actions/runner-images/issues/10636) 

sticky to ubuntu 22.04 for CI 

---

.github/CODEOWNERS
MAINTAINERS.md

This reverts commit 2cc34049feecf39cb20c1fc88985cfd70cf98614.
Reverting last commit to add maintainers

Revert "Updating the maintainers and codeowners list"

---

.github/CODEOWNERS
MAINTAINERS.md

Adding @tandonks @shiv0408 @soosinha to maintainers list.

Adding new maintainers

---

cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
server/routes/transforms.ts

Fixing https://github.com/opensearch-project/index-management-dashboards-plugin/issues/1224

Fixing bug in transform API validation to support index patterns

---

server/models/interfaces.ts
server/services/SnapshotManagementService.ts

Backport https://github.com/opensearch-project/index-management-dashboards-plugin/commit/c459af0d6c6a01d54c25fc8a915d927a34d0f6af from https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1242.

[Backport 2.19] Use cat snapshot to get the number of snapshot for a repo (#1242)

---

public/components/IndexDetail/IndexDetail.tsx
public/containers/IndexForm/__snapshots__/IndexForm.test.tsx.snap
public/pages/CreateComposableTemplate/components/IndexSettings/IndexSettings.tsx
public/pages/CreateDataStream/components/IndexSettings/IndexSettings.tsx
public/pages/CreateIndexTemplate/components/IndexSettings/IndexSettings.tsx
public/pages/CreateIndexTemplate/containers/CreateIndexTemplate/__snapshots__/CreateIndexTemplate.test.tsx.snap
public/pages/CreateIndexTemplate/containers/TemplateDetail/__snapshots__/TemplateDetail.test.tsx.snap
public/pages/Reindex/components/CreateIndexFlyout/__snapshots__/CreateIndexFlyout.test.tsx.snap
public/pages/ShrinkIndex/container/ShrinkIndex/__snapshots__/ShrinkIndex.test.tsx.snap
public/utils/constants.ts

Fix wrong urls to documentation:
- index settings
- create index query params
None

Fix wrong urls to documentation

---

.github/actions/run-cypress-tests/action.yaml
.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml
.github/workflows/verify-binary-installation.yml
babel.config.js
cypress.config.js
cypress/e2e/plugins/index-management-dashboards-plugin/snapshots_spec.js
cypress/e2e/plugins/index-management-dashboards-plugin/split_index.js
cypress/utils/commands.js
opensearch_dashboards.json
package.json
public/components/MonacoJSONEditor/hooks.tsx
public/lib/monaco/json.ts
public/pages/ManagedIndices/containers/ManagedIndices/ManagedIndices.tsx
test/jest.config.js
yarn.lock

- Updated 3.0.0 qualifier from alpha1 to beta1 
- Updated Cypress Version
- Added memory leak prevention in ManagedIndices component by implementing _isMounted flag
- Added proper cleanup in componentWillUnmount
- Added safety checks before setState calls to ensure component is still mounted
- Removed direct import of monaco-editor JSON mode that was causing build issues due to nullish coalescing operator (??)
- Switched to using OpenSearch Dashboards' Monaco wrapper (@osd/monaco) instead of direct monaco-editor imports
Reference: [#1291 ](https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1291)
For more information on following Developer …

Updated 3.0.0 qualifier from alpha1 to beta1
