.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml
opensearch_dashboards.json
package.json

person who certified (a), (b) or (c) and I have not modified
it.
(d) I understand and agree …

Updates versions and fixes the unit test workflow

---

.github/workflows/cypress-workflow.yml
release-notes/create-release-notes.py
release-notes/opendistro-for-elasticsearch-index-management-dashboards-plugin.release-notes-1.0.0.0-beta1.md

N/A
* Fix cypress workflow
* Add release notes
person who certified (a), (b) or (c) and I have …

Fix cypress workflow

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json
release-notes/opensearch-index-management-dashboards-plugin.release-notes-1.0.0.0-beta1.md

N/A
* Bump plugin version to 1.0.0.0-beta1
person who certified (a), (b) or (c) and I have not …

Bump plugin version to 1.0.0.0-beta1

---

README.md
opensearch_dashboards.json
package.json
release-notes/opensearch-index-management-dashboards-plugin.release-notes-1.0.0.0-beta1.md

N/A
* Update plugin id to indexManagementDashboards
person who certified (a), (b) or (c) and I …

Update plugin id to indexManagementDashboards

---

.github/draft-release-notes-config.yml
release-notes/opensearch-index-management-dashboards-plugin.release-notes-1.0.0.0-rc1.md

N/A
* Add rc1 release notes
person who certified (a), (b) or (c) and I have not modified
it. …

Add rc1 release notes

---

.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml
models/interfaces.ts

Signed-off-by: Ashish Agrawal <ashisagr@amazon.com>
N/A
* Bump workflows to run against 1.0 …

Bump workflows to run against 1.0

---

public/pages/CreateTransform/components/DefineTransforms/DefineTransforms.tsx
public/pages/CreateTransform/components/PreviewEmptyPrompt/PreviewEmptyPrompt.tsx
public/pages/CreateTransform/components/PreviewTransform/PreviewTransform.tsx
public/pages/CreateTransform/components/ReviewDefinition/ReviewDefinition.tsx
public/pages/CreateTransform/components/ReviewSchedule/ReviewSchedule.tsx
public/pages/CreateTransform/components/TransformIndices/TransformIndices.tsx
public/pages/CreateTransform/components/TransformOptions/Panels/PercentilePanel/PercentilePanel.tsx
public/pages/CreateTransform/components/TransformOptions/Panels/ScriptedMetricsPanel/ScriptedMetricsPanel.tsx
public/pages/CreateTransform/components/TransformOptions/Panels/ScriptedMetricsPanel/index.ts
public/pages/CreateTransform/components/TransformOptions/TransformOptions.tsx
public/pages/CreateTransform/containers/CreateTransform/CreateTransform.tsx
public/pages/CreateTransform/containers/CreateTransformForm/CreateTransformForm.tsx
public/pages/CreateTransform/containers/DefineTransformsStep/DefineTransformsStep.tsx
public/pages/CreateTransform/containers/DefineTransformsStep/index.ts
public/pages/CreateTransform/containers/ReviewAndCreateStep/ReviewAndCreateStep.tsx
public/pages/CreateTransform/containers/ReviewAndCreateStep/index.ts
public/pages/CreateTransform/containers/SetUpIndicesStep/SetUpIndicesStep.tsx
public/pages/CreateTransform/containers/SetUpIndicesStep/index.ts
public/pages/CreateTransform/containers/SpecifyScheduleStep/SpecifyScheduleStep.tsx
public/pages/CreateTransform/containers/SpecifyScheduleStep/index.ts
public/pages/CreateTransform/index.ts
public/pages/CreateTransform/utils/constants.ts
public/pages/Transforms/components/GeneralInformation/GeneralInformation.tsx
public/pages/Transforms/components/Schedule/Schedule.tsx
public/pages/Transforms/containers/Transforms/EditTransform.tsx
public/pages/Transforms/containers/Transforms/TransformDetails.tsx
public/pages/Transforms/containers/Transforms/TransformSettings.tsx
public/pages/Transforms/containers/Transforms/Transforms.tsx
server/routes/transforms.ts
server/services/TransformService.ts

* Fix preview table toggles
* Fix page size in edit page
* Remove console debug logs
* Fix calling transform preview api with non-empty input
* Fix content in transform preview page in edit section
* Fix percentiles column rendering bug
* Adding refresh button to update the list view 
* Some UX improvements
* Enabling scripted metrics in transform create workflow
license and I have the right under that license …

Transform feature cleanup and bug fixes

---

cypress/fixtures/sample_transform.json
cypress/integration/transforms_spec.js
cypress/support/commands.js
cypress/support/constants.js
cypress/support/index.d.ts
cypress/support/index.js

N/A
Added cypress tests for Transform pages
person who certified (a), (b) or (c) and I have …

Transform cypress tests

---

public/pages/CreateRollup/components/HistogramAndMetrics/HistogramAndMetrics.tsx

Signed-off-by: Ravi Thaluru <ravi1092@gmail.com>
Fix preview of rollup metrics in create workflow
(c) The contribution was provided directly to me by some …

Rollup bugfix

---

public/pages/CreateTransform/components/TransformOptions/TransformOptions.tsx

Signed-off-by: Ravi Thaluru <ravi1092@gmail.com>
N/A
Adding "Group by Terms" option for date fields, number fields when creating transforms
(c) The …

Adding correct dropdown options for different fields in transforms

---

models/interfaces.ts
public/pages/VisualCreatePolicy/components/DraggableAction/DraggableAction.test.tsx
public/pages/VisualCreatePolicy/components/DraggableAction/DraggableAction.tsx
public/pages/VisualCreatePolicy/components/DraggableAction/__snapshots__/DraggableAction.test.tsx.snap
public/pages/VisualCreatePolicy/components/DraggableAction/index.ts
public/pages/VisualCreatePolicy/utils/actions.ts
public/pages/VisualCreatePolicy/utils/constants.ts

Adds draggable action component to reorder actions when creating/editing a state
After All files                                                                             |   48.01 |    41.16 |   44.16 |   48.59 |
DraggableAction.tsx                                                                 |     100 |       50 |     100 | …

Adds draggable action component

---

public/pages/VisualCreatePolicy/components/ChannelNotification/ChannelNotification.test.tsx
public/pages/VisualCreatePolicy/components/ChannelNotification/ChannelNotification.tsx
public/pages/VisualCreatePolicy/components/ChannelNotification/__snapshots__/ChannelNotification.test.tsx.snap
public/pages/VisualCreatePolicy/components/ChannelNotification/index.ts
server/models/interfaces.ts

Adds UI for selecting channels and then adding message
After All files                                                                             |   47.92 |    41.48 |   44.25 |   48.47 |
ChannelNotification.tsx                                                             |     100 |    66.67 |     100 |     100 |
By submitting this pull request, I confirm that my contribution is made under the terms …

Adds new UI for Channel Notification

---

models/interfaces.ts
public/pages/VisualCreatePolicy/components/TimeoutRetrySettings/TimeoutRetrySettings.test.tsx
public/pages/VisualCreatePolicy/components/TimeoutRetrySettings/TimeoutRetrySettings.tsx
public/pages/VisualCreatePolicy/components/TimeoutRetrySettings/__snapshots__/TimeoutRetrySettings.test.tsx.snap
public/pages/VisualCreatePolicy/components/TimeoutRetrySettings/index.ts

Timeout, retry, backoff settings in action flyout.
Still have more tests to write, will do in follow up PR.

Adds timeout retry settings component used in action flyout

---

public/pages/VisualCreatePolicy/components/States/States.test.tsx
public/pages/VisualCreatePolicy/components/States/States.tsx
public/pages/VisualCreatePolicy/components/States/__snapshots__/States.test.tsx.snap
public/pages/VisualCreatePolicy/components/States/index.ts

Adds States UI component

---

public/pages/VisualCreatePolicy/components/ISMTemplates/ISMTemplates.test.tsx
public/pages/VisualCreatePolicy/components/ISMTemplates/ISMTemplates.tsx
public/pages/VisualCreatePolicy/components/ISMTemplates/__snapshots__/ISMTemplates.test.tsx.snap
public/pages/VisualCreatePolicy/components/ISMTemplates/index.ts
public/pages/VisualCreatePolicy/utils/helpers.test.ts
public/pages/VisualCreatePolicy/utils/helpers.ts

Adds ISM Templates UI component

---

public/pages/VisualCreatePolicy/containers/CreateAction/CreateAction.test.tsx
public/pages/VisualCreatePolicy/containers/CreateAction/CreateAction.tsx
public/pages/VisualCreatePolicy/containers/CreateAction/__snapshots__/CreateAction.test.tsx.snap
public/pages/VisualCreatePolicy/containers/CreateAction/index.ts
public/pages/VisualCreatePolicy/utils/helpers.ts

Adds create action container shown in flyout

---

public/pages/VisualCreatePolicy/components/Transition/Transition.test.tsx
public/pages/VisualCreatePolicy/components/Transition/Transition.tsx
public/pages/VisualCreatePolicy/components/Transition/__snapshots__/Transition.test.tsx.snap
public/pages/VisualCreatePolicy/components/Transition/index.ts

Adds transition component

---

public/pages/VisualCreatePolicy/containers/CreateTransition/CreateTransition.test.tsx
public/pages/VisualCreatePolicy/containers/CreateTransition/CreateTransition.tsx
public/pages/VisualCreatePolicy/containers/CreateTransition/__snapshots__/CreateTransition.test.tsx.snap
public/pages/VisualCreatePolicy/containers/CreateTransition/index.ts

Flyout container for create transition UI

Adds create transition container

---

public/components/CreatePolicyModal/CreatePolicyModal.test.tsx
public/components/CreatePolicyModal/CreatePolicyModal.tsx
public/components/CreatePolicyModal/__snapshots__/CreatePolicyModal.test.tsx.snap
public/components/CreatePolicyModal/index.ts
test/mocks/historyMock.ts

Adds modal for choosing between visual and json editor

---

integtest.sh

Provide host parameter in integtest.sh

---

.github/workflows/cypress-workflow.yml
cypress.json
cypress/support/index.js
integtest.sh

Fix integtest.sh security enabled case

---

cypress/integration/managed_indices_spec.js
cypress/integration/rollups_spec.js

Fixing flaky

---

public/components/JSONModal/JSONModal.tsx
public/components/JSONModal/__snapshots__/JSONModal.test.tsx.snap
public/pages/PolicyDetails/components/DeleteModal/DeleteModal.tsx
public/pages/PolicyDetails/components/DeleteModal/__snapshots__/DeleteModal.test.tsx.snap
public/pages/VisualCreatePolicy/components/EuiFormCustomLabel/EuiFormCustomLabel.tsx
public/pages/VisualCreatePolicy/components/EuiFormCustomLabel/__snapshots__/EuiFormCustomLabel.test.tsx.snap
public/pages/VisualCreatePolicy/components/ISMTemplate/ISMTemplate.tsx
public/pages/VisualCreatePolicy/components/ISMTemplate/__snapshots__/ISMTemplate.test.tsx.snap
public/pages/VisualCreatePolicy/components/ISMTemplates/ISMTemplates.tsx
public/pages/VisualCreatePolicy/components/ISMTemplates/__snapshots__/ISMTemplates.test.tsx.snap
public/pages/VisualCreatePolicy/components/PolicyInfo/__snapshots__/PolicyInfo.test.tsx.snap
public/pages/VisualCreatePolicy/components/States/States.tsx
public/pages/VisualCreatePolicy/components/States/__snapshots__/States.test.tsx.snap
public/pages/VisualCreatePolicy/components/TimeoutRetrySettings/__snapshots__/TimeoutRetrySettings.test.tsx.snap
public/pages/VisualCreatePolicy/components/Transition/Transition.tsx
public/pages/VisualCreatePolicy/components/Transition/__snapshots__/Transition.test.tsx.snap
public/pages/VisualCreatePolicy/components/UIActions/RolloverUIAction.tsx
public/pages/VisualCreatePolicy/containers/CreateAction/CreateAction.tsx
public/pages/VisualCreatePolicy/containers/CreateAction/__snapshots__/CreateAction.test.tsx.snap
public/pages/VisualCreatePolicy/containers/CreateState/CreateState.tsx
public/pages/VisualCreatePolicy/containers/CreateState/__snapshots__/Actions.test.tsx.snap
public/pages/VisualCreatePolicy/containers/CreateState/__snapshots__/CreateState.test.tsx.snap
public/pages/VisualCreatePolicy/containers/CreateState/__snapshots__/Transitions.test.tsx.snap
public/pages/VisualCreatePolicy/containers/CreateTransition/CreateTransition.tsx
public/pages/VisualCreatePolicy/containers/CreateTransition/__snapshots__/CreateTransition.test.tsx.snap
public/pages/VisualCreatePolicy/containers/ErrorNotification/ErrorNotification.tsx
public/pages/VisualCreatePolicy/containers/ErrorNotification/__snapshots__/ErrorNotification.test.tsx.snap
public/pages/VisualCreatePolicy/containers/VisualCreatePolicy/VisualCreatePolicy.tsx
public/utils/constants.ts
release-notes/opensearch-index-management-dashboards-plugin.release-notes-1.1.0.0.md

UI fixes from callouts during fit n finish review.
Adds some more learn more links, changes some to link to specific sections.
Fixes some padding, styling, and text content.

Fixes small issues on new ISM UI

---

.github/workflows/cypress-workflow.yml
.github/workflows/links.yml
.github/workflows/unit-tests-workflow.yml
README.md

Reverted wrong part of commit, removes .txt for link checker and adds back the github workflow steps

Revert the correct code..

---

public/pages/VisualCreatePolicy/components/UIActions/NotificationUIAction.tsx

Enable editing the legacy notification action in the visual editor
- [X ] Commits are signed per the DCO using --signoff

Fix the bugs in visual UI for legacy notification

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-1.2.0.0.md

Signed-off-by: Eric Lobdell <lobdelle@amazon.com>
Adds release note file for 1.2.0.0 release
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/98

Add release notes for 1.2.0.0

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-1.2.0.0.md

Backporting release notes from main to 1.2

Add release notes for 1.2.0.0 

---

public/app.scss

Fixes copyright header
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/38

Fixes copyright header

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-1.3.0.0.md

Updates release notes with new commits: 
- Adds support on UI for min primary shard size rollover condition and min rollover age transition condition
- Add backport documentation link
N/A

Updates release notes with new commits

---

.github/workflows/cypress-workflow.yml

Following https://github.com/opensearch-project/opensearch-build/pull/1863, change 2.0-alpha1 to 2.0-rc1.

Change 2.0-alpha1 to 2.0-rc1.

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.0.0.0-rc1.md

Signed-off-by: Clay Downs <downsrob@amazon.com>
Adds release notes for 2.0.0.0-rc1

Adds release notes for 2.0.0.0-rc1

---

server/clusters/ism/ismPlugin.ts

Signed-off-by: Ravi Thaluru <thalurur@users.noreply.github.com>
* fix the URI - remove index_management suffix
N/A

Fix channels URI

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Incremented version to 1.3.2.
Part of https://github.com/opensearch-project/opensearch-build/issues/1882

Incremented version to 1.3.2.

---

.github/workflows/cypress-workflow.yml
package.json
yarn.lock

Continue node removal from https://github.com/opensearch-project/index-management-dashboards-plugin/pull/140
Calming down the [dependabot](https://github.com/opensearch-project/index-management-dashboards-plugin/security/dependabot)
#137 

Wrap up node removal and bump as dependabot suggest

---

package.json
yarn.lock

Backports node removal and version bumps to 2.0 branch.
NA

[BACKPORT] Wrap up node removal and bump as dependabot suggest (#193)

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.0.0.0.md

Signed-off-by: Clay Downs <downsrob@amazon.com>
Adds release notes for 2.0.0
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/191

Adds release notes for 2.0.0

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Signed-off-by: pgodithi <pgodithi@amazon.com>
https://github.com/opensearch-project/opensearch-build/issues/2101
https://github.com/opensearch-project/opensearch-build/issues/2101

Version Increment to 1.3.3 OpenSearch Dashboard release 

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Incremented version to 2.0.1
Part of https://github.com/opensearch-project/opensearch-build/issues/2165

Incremented version to 2.0.1

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.1.0.0.md

Add 2.1.0 release note

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Increment version to 1.3.4
Part of https://github.com/opensearch-project/opensearch-build/issues/2205

Incremented version to 1.3.4.

---

public/pages/CreateRollup/components/RollupIndices/RollupIndices.tsx
public/pages/CreateRollup/containers/CreateRollupForm/__snapshots__/CreateRollupForm.test.tsx.snap

Signed-off-by: AWSHurneyt <hurneyt@amazon.com>
Updated rollup help text.

Updated rollup help text.

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Incremented version to 1.3.5.
Part of: https://github.com/opensearch-project/opensearch-build/issues/2348

[Release 1.3.5] Version increment

---

.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml
test/setup.jest.ts

Pulling changes published in PR https://github.com/opensearch-project/index-management-dashboards-plugin/pull/227 into `2.x`.
1. Adjusted path for a dependency used by unit tests to align with migration from `EUI` to `OUI`.
2. Enabled unit and cypress test workflows on all branches.
3. Adjusted OSD version used by unit and cypress test workflows to align with OSD branching strategy.

Refactored dependency used by test mock. Adjusted OSD version used by test workflows.

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
Version increment 2.2.1
Part of: https://github.com/opensearch-project/opensearch-build/issues/2481

Version increment 2.2.1

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Version increment 2.3.0

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.3.0.0.md

* Added release notes for 2.3
* Remove commit 221, move 229 to Maintenance, add 250 to Documentation
* Move 230 to Maintenance, 229 back to Bug fixes
* Move 229 back to Maintenance
(cherry picked from commit 248a2fe16d05a307837107419cbc4de8d765b6a7)
Signed-off-by: Angie Zhang <langelzh@amazon.com>
For more information on following Developer …

Added release notes for 2.3 (#250)

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.3.0.0.md

Fix header 'Enhancements' in 2.3 release notes.

Add release notes 2.3, add 's' to 'Enhancement' header -> 'Enhancements'

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.3.0.0.md

* Added release notes for 2.3
* Remove commit 221, move 229 to Maintenance, add 250 to Documentation
* Move 230 to Maintenance, 229 back to Bug fixes
* Move 229 back to Maintenance
(cherry picked from commit 248a2fe16d05a307837107419cbc4de8d765b6a7)
Signed-off-by: Angie Zhang <langelzh@amazon.com>
For more information on following Developer …

Added 2.3 release notes for 2.X (#250)

---

README.md

Fixed broken link in 1.3 branch README.

Fixed broken link in 1.3 branch README.

---

.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml
cypress/integration/rollups_spec.js
opensearch_dashboards.json
package.json

Backport - 2.x => 2.4

---

.github/workflows/unit-tests-workflow.yml
package.json
public/pages/CreateTransform/components/TransformIndices/TransformIndices.tsx

Add windows mac OS in CI

---

public/components/AdvancedSettings/AdvancedSettings.test.tsx
public/components/AdvancedSettings/__snapshots__/AdvancedSettings.test.tsx.snap
public/components/AdvancedSettings/index.tsx
public/components/FormGenerator/FormGenerator.test.tsx
public/components/FormGenerator/__snapshots__/FormGenerator.test.tsx.snap
public/components/FormGenerator/built_in_components/index.tsx
public/components/FormGenerator/index.tsx
public/components/JSONEditor/JSONEditor.tsx
public/lib/field/README.md
public/lib/field/index.d.ts
public/lib/field/index.js
public/lib/field/utils.js
public/lib/validate/README.md
public/lib/validate/index.js
public/lib/validate/messages.js
public/lib/validate/rules/format.js
public/lib/validate/rules/index.js
public/lib/validate/rules/length.js
public/lib/validate/rules/pattern.js
public/lib/validate/rules/required.js
public/lib/validate/rules/size.js
public/lib/validate/util.js
public/lib/validate/validator.js
public/pages/CreateIndex/components/IndexDetail/IndexDetail.tsx
public/pages/CreateIndex/containers/CreateIndex/CreateIndex.test.tsx
public/pages/CreateIndex/containers/CreateIndex/__snapshots__/CreateIndex.test.tsx.snap

1. Add a FormGenerator component to quickly setup a form with validation in simple json.
2. Add a AdvancedSettings component for other case to reuse.

feature: Add form generator & advanced settings to speed up development in common form case

---

cypress/integration/indices_spec.js
public/pages/Indices/components/CloseIndexModal/CloseIndexModal.test.tsx
public/pages/Indices/components/CloseIndexModal/CloseIndexModal.tsx
public/pages/Indices/components/CloseIndexModal/__snapshots__/CloseIndexModal.test.tsx.snap
public/pages/Indices/components/CloseIndexModal/index.ts
public/pages/Indices/components/OpenIndexModal/OpenIndexModal.test.tsx
public/pages/Indices/components/OpenIndexModal/OpenIndexModal.tsx
public/pages/Indices/components/OpenIndexModal/__snapshots__/OpenIndexModal.test.tsx.snap
public/pages/Indices/components/OpenIndexModal/index.ts
public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.test.tsx
public/pages/Indices/components/ShrinkIndexFlyout/ShrinkIndexFlyout.tsx
public/pages/Indices/components/ShrinkIndexFlyout/__snapshots__/ShrinkIndexFlyout.test.tsx.snap
public/pages/Indices/components/ShrinkIndexFlyout/constants.ts
public/pages/Indices/components/ShrinkIndexFlyout/index.ts
public/pages/Indices/containers/Indices/Indices.tsx
public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx
public/pages/Indices/containers/IndicesActions/__snapshots__/IndicesActions.test.tsx.snap
public/pages/Indices/containers/IndicesActions/index.tsx
public/utils/constants.ts

Add open&close&shrink index operation to the indices page.

Add open&close&shrink action to indices page

---

cypress/integration/split_index.js
public/components/FormGenerator/built_in_components/index.tsx
public/pages/Indices/components/SplitIndexFlyout/SplitIndexFlyout.test.tsx
public/pages/Indices/components/SplitIndexFlyout/SplitIndexFlyout.tsx
public/pages/Indices/components/SplitIndexFlyout/__snapshots__/SplitIndexFlyout.test.tsx.snap

Signed-off-by: Xuesong Luo <lxuesong@amazon.com>
[Add replica as optional parameter to split index; Provide valid shard number options for user to choose from]
[List any issues this PR will resolve https://github.com/opensearch-project/index-management-dashboards-plugin/issues/393]

Add replica parameter and shard number option list

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Signed-off-by: Rishabh Singh <sngri@amazon.com>
Version bump to 1.3.7

Version bump to 1.3.7

---

public/pages/Indices/components/SplitIndexFlyout/SplitIndexFlyout.test.tsx
public/pages/Indices/components/SplitIndexFlyout/index.ts

feat: update unit test

---

public/pages/CreateIndex/components/IndexDetail/IndexDetail.tsx
public/pages/Reindex/components/IndexSelect/IndexSelect.tsx
public/pages/Reindex/container/Reindex/Reindex.test.tsx
public/pages/Reindex/container/Reindex/Reindex.tsx
public/pages/Reindex/models/interfaces.ts
public/pages/Reindex/utils/constants.ts
public/pages/Reindex/utils/helper.test.ts
public/pages/Reindex/utils/helper.ts
public/utils/constants.ts
server/services/CommonService.ts

- support reindex from single data stream index 
- fix import unwanted setting when create new index

support reindex from single data stream index 

---

.github/workflows/unit-tests-workflow.yml
package.json
public/pages/CreateTransform/components/TransformIndices/TransformIndices.tsx

[1.3] Add windows os for unit tests

[1.3] Add windows os for unit tests

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Signed-off-by: Amardeepsingh Siglani [amardeep7194@gmail.com](mailto:amardeep7194@gmail.com)
Updated cypress-test runner workflow fields to use 1.3 OSD and reference the corresponding branch for ISM plugin.

Update cypress workflow parameters

---

public/pages/Indices/containers/Indices/Indices.tsx
public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx
public/pages/Indices/containers/IndicesActions/__snapshots__/IndicesActions.test.tsx.snap
public/pages/Indices/containers/IndicesActions/index.tsx

Signed-off-by: Xuesong Luo <lxuesong@amazon.com>

Disable Split link for data stream index

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 2.4.1

Bump version to 2.4.1

---

public/components/BetterComboBox/index.tsx
public/components/RemoteSelect/index.tsx
public/components/SimplePopover/SimplePopover.tsx
public/containers/ErrorNotification/ErrorNotification.test.tsx
public/containers/ErrorNotification/__snapshots__/ErrorNotification.test.tsx.snap
public/pages/CreateIndex/components/AliasSelect/index.tsx
public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.test.tsx
public/pages/CreateIndexTemplate/containers/TemplateDetail/__snapshots__/TemplateDetail.test.tsx.snap
public/pages/CreatePolicy/containers/CreatePolicy/CreatePolicy.tsx
public/pages/CreateRollup/components/AdvancedAggregation/AdvancedAggregation.tsx
public/pages/CreateRollup/components/MetricsCalculation/MetricsCalculation.tsx
public/pages/CreateRollup/components/RollupIndices/RollupIndices.tsx
public/pages/CreateRollup/components/TimeAggregations/TimeAggregation.tsx
public/pages/CreateRollup/containers/CreateRollupForm/CreateRollupForm.tsx
public/pages/CreateTransform/components/CreateTransformSteps/CreateTransformSteps.tsx
public/pages/CreateTransform/components/TransformIndices/TransformIndices.tsx
public/pages/CreateTransform/containers/CreateTransformForm/CreateTransformForm.tsx
public/pages/Reindex/components/CreateIndexFlyout/CreateIndexFlyout.test.tsx
public/pages/Reindex/components/CreateIndexFlyout/__snapshots__/CreateIndexFlyout.test.tsx.snap
public/pages/Reindex/components/IndexSelect/IndexSelect.tsx
public/pages/Reindex/container/Reindex/Reindex.tsx
public/pages/Rollups/containers/Rollups/Rollups.tsx
public/pages/VisualCreatePolicy/components/States/State.tsx
public/pages/VisualCreatePolicy/components/States/States.tsx
public/pages/VisualCreatePolicy/containers/ErrorNotification/ErrorNotification.test.tsx
public/pages/VisualCreatePolicy/containers/ErrorNotification/ErrorNotification.tsx

Clean all the unit test warnings

---

cypress/integration/reindex_spec.js
public/pages/Reindex/container/Reindex/Reindex.test.tsx
public/pages/Reindex/container/Reindex/Reindex.tsx
public/pages/Reindex/container/Reindex/__snapshots__/Reindex.test.tsx.snap
public/utils/constants.ts
test/mocks/coreServicesMock.ts

1. remove hardcode links
2. add validation for queryDSL
3. wording change
#449 

wording change

---

public/pages/Reindex/components/IndexSelect/IndexSelect.tsx
public/pages/Reindex/container/Reindex/Reindex.test.tsx
public/pages/Reindex/container/Reindex/Reindex.tsx
public/pages/Reindex/utils/helper.test.ts
public/pages/Reindex/utils/helper.ts

hide overlap items in source and destination in reindex page

hidden overlap items

---

public/pages/Reindex/container/Reindex/Reindex.tsx
public/pages/Reindex/container/Reindex/__snapshots__/Reindex.test.tsx.snap

wording update and dynamic breadcrumbs

wording and breadcrumbs update

---

public/pages/CreateIndex/components/IndexDetail/IndexDetail.tsx
public/pages/IndexDetail/containers/IndexDetail/IndexDetail.tsx
public/pages/Indices/containers/Indices/Indices.tsx
public/pages/Indices/containers/IndicesActions/index.tsx
public/pages/Indices/utils/helpers.ts
public/pages/SplitIndex/components/SplitIndexFlyout/SplitIndexFlyout.tsx
public/pages/SplitIndex/components/SplitIndexForm/SplitIndexForm.tsx
public/pages/SplitIndex/components/SplitIndexForm/index.ts
public/pages/SplitIndex/container/SplitIndex/SplitIndex.test.tsx
public/pages/SplitIndex/container/SplitIndex/SplitIndex.tsx
public/pages/SplitIndex/container/SplitIndex/__snapshots__/SplitIndex.test.tsx.snap
public/utils/constants.ts

[Remove split functions from IndicesActions class; Minor wording change after review; ]

Index operation

---

public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.test.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/__snapshots__/ShrinkIndex.test.tsx.snap

Signed-off-by: Binlong Gao <gbinlong@amazon.com>
1. Rewording some error message.
2. Change the style of the input form in order to make the page consistent with other pages.
#468 

Rewording some error message and fix some tiny issue for shrink page

---

.github/workflows/unit-tests-workflow.yml

feat: fix mac platform error

---

.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml
opensearch_dashboards.json
package.json

Bump to 2.5.0

---

public/JobHandler/index.tsx
public/models/interfaces.ts
public/pages/Reindex/components/IndexSelect/IndexSelect.tsx
public/pages/Reindex/container/Reindex/Reindex.test.tsx
public/pages/Reindex/container/Reindex/Reindex.tsx
public/pages/Reindex/container/Reindex/__snapshots__/Reindex.test.tsx.snap

support detail link for toast and alias

toast link support data stream and alias

---

public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.test.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/__snapshots__/ShrinkIndex.test.tsx.snap

Signed-off-by: gaobinlong <gbinlong@amazon.com>
1. Chnage some wording in the shrink index page.
2. Modify related unit test code.

Change some wording in shrink index page

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.5.0.0.md

2.5 release note

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Fix plugin version format

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Signed-off-by: Divya Madala <divyaasm@amazon.com>
Incremented version from 1.3.7 to 1.3.8

Increment version to 1.3.8

---

.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml
opensearch_dashboards.json
package.json

Bumped version to 2.6.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/628

Bumped version to 2.6.

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.6.0.0.md

Drafted 2.6 release notes.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/628

Drafted 2.6 release notes.

---

.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml
cypress/integration/force_merge.js
public/components/FormGenerator/built_in_components/index.tsx
public/pages/ForceMerge/components/ForceMergeAdvancedOptions/ForceMergeAdvancedOptions.test.tsx
public/pages/ForceMerge/components/ForceMergeAdvancedOptions/ForceMergeAdvancedOptions.tsx
public/pages/ForceMerge/components/ForceMergeAdvancedOptions/__snapshots__/ForceMergeAdvancedOptions.test.tsx.snap
public/pages/ForceMerge/components/ForceMergeAdvancedOptions/index.ts
public/pages/ForceMerge/components/IndexSelect/IndexSelect.test.tsx
public/pages/ForceMerge/components/IndexSelect/IndexSelect.tsx
public/pages/ForceMerge/components/IndexSelect/__snapshots__/IndexSelect.test.tsx.snap
public/pages/ForceMerge/components/IndexSelect/index.ts
public/pages/ForceMerge/components/SwitchNumber/index.tsx
public/pages/ForceMerge/container/ForceMerge/ForceMerge.test.tsx
public/pages/ForceMerge/container/ForceMerge/ForceMerge.tsx
public/pages/ForceMerge/container/ForceMerge/__snapshots__/ForceMerge.test.tsx.snap
public/pages/ForceMerge/container/ForceMerge/index.ts
public/pages/ForceMerge/index.ts
public/pages/ForceMerge/models/interfaces.ts
public/pages/ForceMerge/utils/constants.ts
public/pages/ForceMerge/utils/helper.test.ts
public/pages/ForceMerge/utils/helper.ts
public/pages/Indices/containers/IndicesActions/index.tsx
public/pages/Main/Main.tsx
public/utils/constants.ts

* temp: save
* feat: update
* feat: add validator
* feat: add unit test
* feat: add unit test
* feat: add cypress test
* feat: try to get cypress test start
* feat: update
* feat: force merge optimize
* feat: modify toast message
* feat: update
* feat: update
* feat: update
Signed-off-by: …

[Backport main]Feature: force merge (#608)

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.6.0.0.md

2.6 release note 

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Signed-off-by: Divya Madala <divyaasm@amazon.com>
Bump version from 1.3.8 to 1.3.9 

Increment version to 1.3.9

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
server/services/IndexService.ts

[BUG]Add downgrade logic when fetching indexes 

---

server/services/IndexService.ts

* feat: add catch
* feat: bump version to 2.7
* Revert "feat: bump version to 2.7"
This reverts commit ca05a0321fc2a8673d18e40afd5588bf52135934.
* feat: update flow to 2.6
---------
(cherry picked from commit 9e68dc10f252e65bd75bd9e9941bb0b9d1a62ba7) …

[BUG]Add downgrade logic when fetching indexes  (#684)

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.7.0.0.md

Add release note of 2.7

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.7.0.0.md

Updated 2.7 release notes.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/691

Updated 2.7 release notes.

---

public/utils/constants.ts
public/utils/helpers.test.ts
public/utils/helpers.ts

used for flush/refresh/clear cache

Common funcs for filter block indices

---

.github/CODEOWNERS
MAINTAINERS.md

Updating the MAINTAINERS.md and CODEOWNERS file
Closes #610 

Updating the maintainers and CODEOWNERS file

---

.github/CODEOWNERS
MAINTAINERS.md

Add more maintainers & code owners

---

.github/workflows/cypress-workflow.yml

Add more wait time to make cypress tests pass

---

server/services/CommonService.ts

Update path parameter to follow RFC/generic HTTP convention

---

server/services/CommonService.ts

* Update path parameter to follow RFC/generic HTTP convention
* Update path parameter to follow RFC/generic HTTP convention
---------
(cherry picked from commit a4a6a8daf1600550188ceda029b9e07b4ca3371b)

Update path parameter to follow RFC/generic HTTP convention (#737)

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.8.0.0.md

[Add 2.8 release notes]
[[List any issues this PR will resolve]](https://github.com/opensearch-project/index-management-dashboards-plugin/issues/749)

Add 2.8 release notes

---

public/containers/RefreshAction/index.tsx
public/pages/Indices/containers/IndicesActions/IndicesActions.test.tsx
release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.8.0.0.md

[Update release note with original PR numbers to follow standard and add red status index names to toast message if refresh index fail.]

Update release note and minor change to toast message.

---

.github/workflows/cypress-workflow.yml
release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.8.0.0.md

* Use noloop host
* feat: update release-notes
---------
(cherry picked from commit b0ee09bd076eaab5643cfedfab1051be5ed9ba96)

[Backport 2.8] Fix CI on Node.js v18 (#785)

---

.github/workflows/cypress-workflow.yml
release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.8.0.0.md

* Use noloop host
* feat: update release-notes
---------
(cherry picked from commit b0ee09bd076eaab5643cfedfab1051be5ed9ba96)

[Backport 2.x] Fix CI on Node.js v18 (#785)

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.9.0.0.md

Added 2.9 release notes.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/796

Added 2.9 release notes.

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump to 2.4.2

Bump to 2.4.2

---

.github/workflows/cypress-workflow.yml
opensearch_dashboards.json
package.json

Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Bump version to 2.3.1 to prepare for next patch.

Bump version to 2.3.1

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.10.0.0.md

Added 2.10 release notes

---

.github/CODEOWNERS
MAINTAINERS.md

Update codeowners and maintainers list
N/A

Update codeowners and maintainers list

---

DEVELOPER_GUIDE.md

Adds the necessary command for testing using `Cypress` on `localhost`
#916 

added server.host to dev guide

---

.github/CODEOWNERS
MAINTAINERS.md

Adding `Rohit Ashiwal` as code owner.

add Rohit Ashiwal as code owner

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.12.0.0.md

Update release notes for `v2.12.0`.
#894

Add v2.12.0 Release Notes

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.12.0.0.md

Add CVE updates to release ntoes.
#971

Update v2.12.0 Release Notes

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.13.0.0.md

Update release notes for v2.13.0.
#975 

Add v2.13.0 Release Notes

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.14.0.0.md

Add release notes for 2.14

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.15.0.0.md

Add release notes for 2.15

---

MAINTAINERS.md

Adding maintainer
N/A
- [✅] Commits are signed per the DCO using --signoff

Maintainer addition

---

public/pages/CreateSnapshotPolicy/containers/CreateSnapshotPolicy/CreateSnapshotPolicy.tsx
public/pages/Main/Main.tsx
public/pages/Repositories/components/CreateRepositoryFlyout/CreateRepositoryFlyout.tsx
public/pages/Repositories/containers/Repositories/Repositories.tsx
public/pages/SnapshotPolicies/containers/SnapshotPolicies/SnapshotPolicies.tsx
public/pages/SnapshotPolicyDetails/containers/SnapshotPolicyDetails/SnapshotPolicyDetails.tsx
public/pages/Snapshots/components/CreateSnapshotFlyout/CreateSnapshotFlyout.tsx
public/pages/Snapshots/components/RestoreSnapshotFlyout/RestoreSnapshotFlyout.tsx
public/pages/Snapshots/components/SnapshotFlyout/SnapshotFlyout.tsx
public/pages/Snapshots/containers/Snapshots/Snapshots.tsx
public/services/SnapshotManagementService.ts
server/plugin.ts
server/routes/snapshotManagement.ts
server/services/SnapshotManagementService.ts

With this change we add MDS support to snapshot pages. 
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/1067
https://github.com/user-attachments/assets/71ee85f3-a387-49ad-973e-aeffe360ff0d

Add MDS support to snapshot pages

---

public/plugin.ts

Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
(cherry picked from commit 7565bcd9e7f7ec56cc88bdfdb41e77e37284efbd)

feat: reuse applications (#1094)

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.16.0.0.md

Added release notes for 2.16
NA

Added release notes for v2.16

---

public/plugin.ts

Change the title / description / categories of the features to comply with new design in 2.17.

[navigation]feat: reorder features and rename title and description

---

public/components/SwitchableEditor/__snapshots__/SwitchableEditor.test.tsx.snap
public/pages/CreateComposableTemplate/containers/CreateComposableTemplate/__snapshots__/CreateComposableTemplate.test.tsx.snap
public/pages/CreateComposableTemplate/containers/TemplateDetail/__snapshots__/TemplateDetail.test.tsx.snap
public/pages/Indices/components/IndexControls/__snapshots__/IndexControls.test.tsx.snap
public/pages/Indices/containers/Indices/__snapshots__/Indices.test.tsx.snap
public/pages/ManagedIndices/components/ManagedIndexControls/__snapshots__/ManagedIndexControls.test.tsx.snap
public/pages/ManagedIndices/containers/ManagedIndices/__snapshots__/ManagedIndices.test.tsx.snap
public/pages/Templates/containers/AssociatedComponentsModal/__snapshots__/AssociatedComponentsModal.test.tsx.snap
public/pages/VisualCreatePolicy/components/UIActions/AliasUIAction/__snapshots__/AliasUIAction.test.tsx.snap

This PR updates snapshots of pages so that UT can pass with latest changes.
output of `yarn run test:jest -u `
```
Snapshot Summary
› 13 snapshots updated from 9 test suites.
Test Suites: 159 passed, 159 total
Tests:       626 passed, 626 total
Snapshots:   13 updated, 195 passed, 208 total
Time:        47.351 s, estimated 49 s
Ran all test suites.
✨  Done in 48.49s.
```

Update pages snapshots

---

public/pages/Templates/containers/AssociatedComponentsModal/AssociatedComponentsModal.test.tsx
public/pages/Templates/containers/AssociatedComponentsModal/__snapshots__/AssociatedComponentsModal.test.tsx.snap

This PR adds fix for `AssociatedComponentsModal` snapshot test failure
NA

Fix for snapshot tests race condition

---

opensearch_dashboards.json
public/components/ContentPanel/ContentPanel.tsx
public/pages/CreateSnapshotPolicy/containers/CreateSnapshotPolicy/CreateSnapshotPolicy.tsx
public/pages/Main/Main.tsx
public/pages/Repositories/containers/Repositories/Repositories.tsx
public/pages/SnapshotPolicies/containers/SnapshotPolicies/SnapshotPolicies.tsx
public/pages/SnapshotPolicyDetails/containers/SnapshotPolicyDetails/SnapshotPolicyDetails.tsx
public/pages/Snapshots/components/RestoreActivitiesPanel/RestoreActivitiesPanel.tsx
public/pages/Snapshots/containers/Snapshots/Snapshots.tsx
public/pages/utils/display-utils.tsx
public/plugin.ts
public/services/Services.ts
public/utils/constants.ts

[Backport-2x] Update newHeader for Snapshot pages (#1105)- https://github.com/opensearch-project/index-management-dashboards-plugin/commit/c486b61345ee3411a6fa9f162180d807d5d9e8ea
There were conflicts in ```opensearch_dashboard.yml```  file..

[Backport-2x] Update newHeader for Snapshot pages (#1105)

---

public/pages/Notifications/containers/Notifications/Notifications.test.tsx
public/pages/Notifications/containers/Notifications/Notifications.tsx
public/utils/constants.ts

Update new header for notification settings page in ISM.
NOTE: Please merge this PR after this dependent PR is merged: https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1121
OLD UI
NEW UI

Update new header for notification settings page in ISM

---

public/components/CustomLabel/CustomLabel.tsx
public/pages/CreateSnapshotPolicy/components/SnapshotAdvancedSettings/SnapshotAdvancedSettings.tsx
public/pages/CreateSnapshotPolicy/containers/CreateSnapshotPolicy/CreateSnapshotPolicy.tsx
public/pages/Reindex/components/CreateIndexFlyout/__snapshots__/CreateIndexFlyout.test.tsx.snap
public/pages/Repositories/components/CreateRepositoryFlyout/CreateRepositoryFlyout.tsx
public/pages/Repositories/components/DeleteModal/DeleteModal.tsx
public/pages/Repositories/containers/Repositories/Repositories.tsx
public/pages/SnapshotPolicies/containers/SnapshotPolicies/SnapshotPolicies.tsx
public/pages/SnapshotPolicyDetails/containers/SnapshotPolicyDetails/SnapshotPolicyDetails.tsx
public/pages/Snapshots/components/AddPrefixInput/__snapshots__/AddPrefixInput.test.tsx.snap
public/pages/Snapshots/components/CreateSnapshotFlyout/CreateSnapshotFlyout.tsx
public/pages/Snapshots/components/RenameInput/RenameInput.tsx
public/pages/Snapshots/components/RenameInput/__snapshots__/RenameInput.test.tsx.snap
public/pages/Snapshots/components/RestoreActivitiesPanel/RestoreActivitiesPanel.tsx
public/pages/Snapshots/components/RestoreSnapshotFlyout/RestoreSnapshotFlyout.tsx
public/pages/Snapshots/components/SnapshotFlyout/SnapshotFlyout.tsx
public/pages/Snapshots/components/SnapshotRenameOptions/SnapshotRenameOptions.tsx
public/pages/Snapshots/components/SnapshotRenameOptions/__snapshots__/SnapshotRenameOptions.test.tsx.snap
public/pages/Snapshots/components/SnapshotRestoreAdvancedOptions/SnapshotRestoreAdvancedOptions.tsx
public/pages/Snapshots/components/SnapshotRestoreOption/SnapshotRestoreOption.tsx
public/pages/Snapshots/components/SnapshotRestoreOption/__snapshots__/SnapshotRestoreOption.test.tsx.snap
public/pages/Snapshots/containers/Snapshots/Snapshots.tsx
public/pages/Snapshots/helper.tsx
public/pages/VisualCreatePolicy/components/FlyoutFooter/FlyoutFooter.tsx
public/pages/VisualCreatePolicy/components/FlyoutFooter/__snapshots__/FlyoutFooter.test.tsx.snap

This PR tried to make Fit and Finish changes for the snapshot management pages.
1. Index Snapshots
2. Snapshot policies.
3. Snapshot repositories.
https://github.com/user-attachments/assets/cdb3a1d3-a515-4a37-b7b8-2b1a19d15c99

Fit and Finish Changes for Snapshot Management Pages

---

public/pages/Aliases/containers/AliasActions/index.tsx
public/pages/Aliases/containers/CreateAlias/__snapshots__/CreateAlias.test.tsx.snap
public/pages/Aliases/containers/CreateAlias/index.tsx
public/pages/ChangePolicy/containers/ChangePolicy/ChangePolicy.tsx
public/pages/ChangePolicy/containers/ChangePolicy/__snapshots__/ChangePolicy.test.tsx.snap
public/pages/CreateIndex/containers/IndexForm/index.tsx
public/pages/CreateIndexTemplate/containers/TemplateDetail/TemplateDetail.tsx
public/pages/CreateIndexTemplate/containers/TemplateDetail/__snapshots__/TemplateDetail.test.tsx.snap
public/pages/CreateSnapshotPolicy/components/CronSchedule/CronSchedule.tsx
public/pages/Indices/containers/IndicesActions/index.tsx
public/pages/ManagedIndices/components/ManagedIndexControls/ManagedIndexControls.tsx
public/pages/ManagedIndices/containers/ManagedIndices/ManagedIndices.tsx
public/pages/Reindex/container/Reindex/Reindex.tsx
public/pages/Reindex/container/Reindex/__snapshots__/Reindex.test.tsx.snap
public/pages/RollupDetails/containers/RollupDetails/RollupDetails.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/ShrinkIndex.tsx
public/pages/ShrinkIndex/container/ShrinkIndex/__snapshots__/ShrinkIndex.test.tsx.snap
public/pages/SplitIndex/components/SplitIndexForm/SplitIndexForm.tsx
public/pages/Templates/containers/TemplatesActions/index.tsx
public/pages/Transforms/containers/Transforms/EditTransform.tsx
public/pages/Transforms/containers/Transforms/TransformDetails.tsx
public/pages/Transforms/containers/Transforms/Transforms.tsx
public/pages/Transforms/containers/Transforms/__snapshots__/EditTransform.test.tsx.snap

Backport https://github.com/opensearch-project/index-management-dashboards-plugin/commit/3c1c7a37eb6d1ba610b707b09eedf199c0568385 from https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1166

[Backport 2.17] Fixed bugs in history navigation in rollups and transform jobs pages and some UI changes

---

public/pages/Main/Main.tsx

Fixing a bug with initial data source being set to local cluster

Fixing a bug with initial data source being set to local cluster

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.18.0.0.md

Added release notes for v2.18

---

MAINTAINERS.md

Adding 2 maintainers for this plugin repo

Updating maintainers list

---

MAINTAINERS.md

Adding a maintainer for the repository

Adding maintainer for the repository

---

.github/CODEOWNERS
MAINTAINERS.md

Reverting last 3 PRs for adding maintainers

Revert last 3 PRs for adding maintainers

---

.github/CODEOWNERS
MAINTAINERS.md

Syncing the Maintainers and codeowner files to make it same as main branch after they are updated in #1235

Sync maintainers of 2.x with main

---

cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
server/routes/transforms.ts

Backport https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1237 to 2.x
---------

[Backport 2.x] Fixing bug in transform API validation to support index patterns (#1237)

---

.github/actions/run-cypress-tests/action.yaml
package.json
yarn.lock

Bump cross-spawn to 7.0.5 for fixing CVE-2024-21538

Fixing CVE 2024-21538

---

package.json
yarn.lock

[Backport 2.19] Backport 1258 to 2.19

---

.github/workflows/verify-binary-installation.yml
opensearch_dashboards.json
package.json

Updated Version to 3.0.0.0-alpha1

Index Management Dashboards plugin to version 3.0.0.0-alpha1

---

package.json
yarn.lock

Updated Micromatch new version

---

package.json
yarn.lock

[Backport 2.19] Updated Micromatch new version [(#1273)](https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1273)
Added Micromatch resolution in package.json

 [Backport 2.19] Updated Micromatch new version (#1273)

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-2.19.1.0.md

Add release notes for 2.19.1

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-3.0.0.0-alpha1.md

Added release notes for v3.0.0-alpha1
- [] Commits are signed per the DCO using --signoff

Added release notes for v3.0.0-alpha1

---

package.json
yarn.lock

Fixed CVE: Updated elliptic dependency resolution
Fix: Update elliptic dependency resolution to patch ECDSA private key vulnerability

Fixed CVE: Updated elliptic dependency resolution

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-3.0.0.0-beta1.md

Added Release Notes for v3.0.0-beta1

Added Release Notes for v3.0.0-beta1

---

package.json
release-notes/opensearch-index-management-dashboards-plugin.release-notes-3.0.0.0-beta1.md
yarn.lock

Fixed CVE : babel dependencies
Continution to PR : https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1296

Fixed CVE : babel dependencies

---

.github/workflows/verify-binary-installation.yml
release-notes/opensearch-index-management-dashboards-plugin.release-notes-3.0.0.0.md

Added Release Notes for v3.0.0

Added Release Notes for v3.0.0

---

.github/workflows/verify-binary-installation.yml

Fixed verify-binary-installation workflow file

Fixed verify-binary-installation workflow file

---

release-notes/opensearch-index-management-dashboards-plugin.release-notes-3.1.0.0.md

Added Release Notes for v3.1.0

Added Release Notes for v3.1.0

---

.github/workflows/cypress-workflow.yml
.github/workflows/unit-tests-workflow.yml
package.json
yarn.lock

Fixed CVE: babel dependencies & elliptic dependency

Fixed CVE: babel dependencies & elliptic dependency

---

README.md
package.json
yarn.lock

Resolve pbkdf2 to resolve CVE-2025-6545 CVE-2025-6547
#1333 

Resolve pbkdf2 to resolve CVE-2025-6545 CVE-2025-6547

---

package.json
yarn.lock

Fixing #CVE-2025-7783

---

package.json
yarn.lock

Fixing CVE-2025-9287 CVE-2025-9288

Fixing CVE-2025-9287 CVE-2025-9288
